### ISSUE TITLE
Sprint 6: Conduct Research and Create Synthesis

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#10]
# Outcome
Conduct interviews with current customers and debrief amongst team.

# Features

*Foundational*

- [x] #9 
- [x] Conduct Interviews
- [ ] Conduct initial, top-line synthesis (conducted during debriefs)

Done = We have good initial insights from existing customers into how we can improve the experience for learning about, requesting, and managing a domain that can directly inform our content and features.

*Next*

- [ ] Collaborative synthesis
- [ ] Outcomes

**Comment by colinmurphy01** [comment]
If anyone would like to moderate a session, work with @boonerang to get on the schedule and prep.

**Comment by calerubensteingsa** [comment]
Working session next week for synthesis

**Comment by calerubensteingsa** [comment]
Archiving #134 as it is a dupe

**Comment by calerubensteingsa** [comment]
10/3:

- One more person coming in, keeping it rolling
- May share synthesis doc, might be this is more foundational
- Instead of boxing it to round, keep it foundation

**Comment by calerubensteingsa** [comment]
10/6:

- Someone is connecting us inside somewhere, working on getting timeframe - pulling out testing scenarios for usability and testing, can include in equity pause - digging through past usability tests
- Will drop in channel later regarding some testing
- Digging into panel logistics, may need to touchbase with PRA lawyers - writing up what that will be

**Comment by loganmeetsworld** [comment]
@boonerang to create new tickets around customer panels, touchpoints setup (method to talk to folks), work to solicit and find participants
