### ISSUE TITLE
Domain Mgmt: Create Usability Test Plan

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#1009]
### Issue Description

Create a plan for testing the Domain Mgmt section with users.

**Acceptance Criteria**
1) Define and document the following:

- **Goals:** What are we hoping to achieve with the research?
- **Participants:** Who are we recruiting? What's the process and what materials do we need for this (e.g. an intro email?)
- **Script / Questions:** What are we asking users? What tasks do we want users to complete?
- **Insights:** How will we capture and prioritize insights and/or bugs
- **Timeline:** Define a timeline for recruiting, conducting research, compiling insights, and implementing top-priority findings

2) Create tickets for next steps (recruiting participants, conducting the research, etc)

**Comment by brooksr4** [comment]
Potential Goals for testing (9/19 Product/Design Huddle):
Partially Filled applications, Statuses for the Domain, Entering DNS Information
