### ISSUE TITLE
Update /availability API to pull from new registry

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/getgov#1015]
### Issue Description

The [current API](https://github.com/cisagov/getgov/blob/784cc0f618e056c262512d688e8e4316dd25c9e4/src/api/views.py#L14) consists of a second-hand pull of canonical data that the .gov program [publishes to GitHub](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv). Change this implementation so that queries poll the new registry/Whois/RDAP.

### Acceptance Criteria

- [x] The checkDomain method is used to check that a domain is in the registry or not

and

- [x] The check is used at /availability 
- [x] Tests are implemented and/or updated
- [ ]  In the new domain application flow, where a user is checking if a domain is available for use, it should now use this /availability endpoint (if not already) and tests should be updated to check that /availability and epp is being triggered on this page as well. 

### Additional Context (optional)

Once done, the backend work of #476 and frontend work of #561 can be completed.

_Consider add-on to defend the endpoint from bot spam._

### Implementation Notes

Epp has a check command that can be run with just the name of a given domain.  This should be used as the method for checking the desired domain at this endpoint.

### Issue Links

Blocking #476 and #561
Blocked by #1028

**Comment by PaulKuykendall** [comment]
In refinement, 

- security? prevent too many calls
-

**Comment by abroddrick** [comment]
Just some background

src/registrar/config/urls.py sets available endpoint and ties it to the "available" function in the api library
find this line:
path("api/v1/available/<domain>", available, name="available"),

The api library defines a function available under src/api/views
->note it requires a user to be logged in to access this endpoint as is (we may want to change this)
- this function calls in_domains which calls _domains(). "_domains" is where you want to remove the communication with github. In it's place you will use Domain.available(). (surround it with a try and catch as errors can occur).
