### ISSUE TITLE
UI Dev: Update DNS name server and host IPs

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#1016]
### Story

As a domain manager OR CISA Analyst,
I want update DNS configuration data for a particular domain
so that the Registry is properly configured, and my website is findable.

### Acceptance Criteria

- [ ] Implement design created in #893 specific to Name Server and Host IPs data entry.  Please look at the revised panel for nameservers when implementing. 
- [ ] include the validations that are covered in the figma
- [ ] When a user enters data for Ips containing whitespaces, this should not result in errors. This may be handled on the front end or backend and is up to the implementers.

### Additional Context

DNSSEC work has been split into a separate page to improve delivery time. (#1091)

### Issue Links
Figma Designs: [Name servers page](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=1493-95184&mode=design)
Depends on #893 
Relates to #919 (which applies constraints to this data entry)
Relates to #1036 (to be implemented later)
Split DNSSEC to #1091 
Relates to #1104 
Relates to #433

**Comment by abroddrick** [comment]
@PaulKuykendall We removed one of your ACs please verify that the above makes sense, and if you agree we can remove the refinement label

**Comment by PaulKuykendall** [comment]
Yes, that makes sense. I'll make a "later" ticket to perform the validation. (I believe that Verisign does this today)
It will be a good check to have in place.
