### ISSUE TITLE
Implement logging to capture changes made to Groups and Permissions, Refactor Groups and Permissions

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#1027]
### Issue Description

User roles/permissions should be handled in django admin groups and changes made to django-admin  groups must be logged. 

The log should contain an identifier of who made the change and what was changed. The log doesn't need to necessarily be in human readable format. Example: Timestamp: UUID 555555 has edited role 983 with attribute x y z.

### Acceptance Criteria

- [x] Log entry is made when a Group is created or deleted
- [x] Log entry is made when a permission is changed on a Group or a User
- [x] implement Groups with full permissions and analyst permissions in models and migrations
- [x] change fixtures to assign full permissions Group to perviously superusers and analyst permission group to previously staff (all fixtures users will be staff)
- [x] Refactor instances in admin.py where we are testing for is_staff or is_superuser to set permissions
- [ ] Refactor unit tests
- [x] Separate users and DAs/Domains fixtures
- [x] divide fixtures into 2 scripts, with one specific to users

### Additional Context (optional)

https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1694718697209909

**Comment by rachidatecs** [comment]
Option2: Hide groups and the option to manage individual perms on users. The built-in Django roles are pre-set with the right perms in fixtures. Trivial effort to do the hiding.

Put another way: we should start by discussing our current implementation that does not use groups or permission setting in django admin.
