### ISSUE TITLE
500 error when using 'Manage Domain' for Domains with no Application Type

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/getgov#1033]
### Current Behavior

An edge case exists where a domain may be created with no associated DomainApplication object. When using the 'Manage Domain' button for these objects, the application returns a 500 error.

### Expected Behavior

No error occurs when clicking the 'Manage Domain' button for Domains with no associated DomainApplication object

### Steps to Reproduce

1. Navigate to /admin
2. Click the '+ add' button next to domain
![image](https://github.com/cisagov/getgov/assets/141044360/eec5c284-f5f7-4128-ac13-19a520f91a35)
3. Create a new Domain
4. Click 'Manage Domain'
5. Error appears
 

### Additional Context
See this slack [thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1694809792692799) for further context.
![image](https://github.com/cisagov/getgov/assets/141044360/440e7e84-4b57-4958-a951-87c86f2d0e51)
![image](https://github.com/cisagov/getgov/assets/141044360/dcd5b718-7137-4bca-8aee-389a0191437c)

This was discussed in engineering huddle and there was an agreement that the model should be changed so that domain application can be null. without throwing any errors on the domain management page

**Comment by abroddrick** [comment]
@zandercymatics this has your name on it, are you working on it?

**Comment by zandercymatics** [comment]
@abroddrick I've got some in-progress work lying around locally, I'll push this up as a draft. My priority got shifted elsewhere with the getters / health check stuff... This is something I can probably work concurrently on (to finish) this upcoming sprint
