### ISSUE TITLE
Provide a history section to inform domain managers of updates to their domain

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/getgov#1070]
### Issue Description

When domain managers make updates to their domain (update DNS, org address, authorizing official, contact info, security email, use management) provide a log of recorded changes in some sort of a "history" section for registrants to see how their domain info has changed over time.

**Comment by PaulKuykendall** [comment]
@PaulKuykendall - check for dupe ticket

**Comment by PaulKuykendall** [comment]
Closed as dupe of #1088, and rolled in Description above to the other ticket
