### ISSUE TITLE
Registrant Content: Organize and Prioritize Story Maps

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#108]
Objective: List of Stories in Story Map is grouped and prioritized to inform content

Done when:

- [x] Story map for new registrant content is prioritized

- [x] Shared with group

- [ ] Review and agree on determine what is high, review if anything is missing, identify what is safe to move forward with, priority

**Comment by michelle-rago** [comment]
[Spreadsheet with user stories](https://docs.google.com/spreadsheets/d/1KBOwM0lDBWtkwHQ4X2P2G0Yo3ZwGgP8PUmfFGYPNZ-E/edit#gid=1971425000)

**Comment by calerubensteingsa** [comment]
9/22

- Posted in Slack
- Seamus added comments, anyone else invited to
- Agreeing on high priority

More input maybe not that crucial - individual user stories line up to pieces of content. Seamus asked for more clarity on user story.

Never really validated user stories. As we move forward and keep clarifying, things will shake out.
