### ISSUE TITLE
Django Admin: Update text and status messaging for "get status" button

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#1096]
### Issue Description

In Django admin, on the Domain page, there is a button to "get status."

- Update text on the "get status" button to read: "Get registry status"
- Update other buttons on this page to use sentence case, as well; "Manage domain" and ~"Delete registry domain"~ "Delete domain in registry"
- Update the status message that appears upon clicking the button to explain what status is being represented.

### Additional Context (optional)

Status message should read: ~"The registry statuses are ['serverTransferProhibited', 'inactive']. These statuses are from the EPP provider of the .gov registry."~
"The registry statuses are ['serverTransferProhibited', 'inactive']. These statuses are from the EPP provider of the .gov registry."

**Comment by abroddrick** [comment]
Suggesting phrasing it as "The registry statuses are ['serverTransferProhibited', 'inactive']. These statuses are from the provider of the .gov registry."

**Comment by abroddrick** [comment]
I see the thumbs up so I am updating it above accordingly

**Comment by zandercymatics** [comment]
Updated AC for the delete button per @Katherine-Osos approval, as the text now reads "Delete domain in registry"

**Comment by vickyszuchin** [comment]
Moved from sprint 31 to sprint 30 per developer approval.
