### ISSUE TITLE
Start creating educational copy for new registrant content

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#110]
- Identify first set of pages; get agreement from team
- Draft content
- Share for review and comment

Objective:

- Start creating content for get.gov based on knowledge and policy changes

Done when:

- Initial content is shared with group

**Links to draft content**
- [Before you request a domain](https://docs.google.com/document/d/1_P7W-kuBflak7opYK_M5wjYs3xJIFKE64hbBxqX9Mvg/edit#)
- [Domain request form](https://docs.google.com/document/d/1GBMQPTD4HXmnvWzg7xzlfgmIfRk0xzhXthy38lrbvIM/edit#) 
- [Benefits of a .gov domain](https://docs.google.com/document/d/1HG6USwit-Uw52yp_jXaGxrLpbp8JqOqj5e4gIVeJBr0/edit#)

**Comment by calerubensteingsa** [comment]
9/22

Supporting content for form and what info they need before form.

**Comment by calerubensteingsa** [comment]
9/27:

- Right now, focused on what people need to do before they complete the form - if they are the type that want to assemble what they need. Just like the domain request form, dependent on what we're implementing

**Comment by calerubensteingsa** [comment]
- Open questions in document
- Everyone is welcome to make comments, still in draft, make sure we're applying what we learned in co-work
- What are the open questions

**Comment by calerubensteingsa** [comment]
10/3:

Ongoing - how do we want to represent this work?

For this upcoming sprint, carry it over

**Comment by calerubensteingsa** [comment]
10/4:

Keep putting links to content, will periodically put in Slack as well

**Comment by calerubensteingsa** [comment]
10/6:

Updating what is already there, elections deprioritized

**Comment by loganmeetsworld** [comment]
10/13

It's been started - so closing out this ticket. Most work is related to the domain request form re: content. @michelle-rago to make a ticket related to educational/theme-focussed content tickets
