### ISSUE TITLE
Design: Show Registry statuses to an analyst

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#1105]
### Issue Description

We already have a "state" for a domain such as DNS Needed, On Hold, Ready etc. However, our registry has a "status" for the domain within its own system that is different and usually a list a values such as active, inactive, etc. A complete list of these registry specific status values can be found [online](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en). 

An _analyst_ may wish to see these statuses just like they are able to see them in the current system. Seeing these values may help with troubleshooting when a user messages about having issues with their domain.

Currently there is a Get EPP Status button on the domain page on django admin which does allow an analyst to see the status of a domain, but is not a very pretty  solution. It has been suggested that we could just display them nicely on the domain management page, however this ticket should decide on the design.

AC:

- [ ] determine if the current button is sufficient as is
- [ ] determine if only analysts or both analysts and registrants should see the registry status
- [ ] if the current the button setup is deemed insufficient: create design/content in figma and link this in a follow on dev ticket

### Additional Context (optional)

We changed to using the On Hold state for our domain which only correlates to the EPP status clienthold, but the server _can_ set a status of serverhold which both an analyst and registrant may want to know about. Without statuses visible to the _registrant_ they will not see if their domain has a serverhold set on it. For the transition and the next few months, this is unlikely to be an issue.

**Comment by abroddrick** [comment]
@Katherine-Osos does this make sense?

**Comment by PaulKuykendall** [comment]
IN refinement, team decided to close, won't do.
