### ISSUE TITLE
Low-fidelity Wireframe for new domain request form - V1

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#113]
Objective:

- Create a low-fidelity wireframe for the domain request form
- Get feedback to continue iteration

Done when:
- Team has given feedback

[Content for domain request form](https://docs.google.com/document/d/1GBMQPTD4HXmnvWzg7xzlfgmIfRk0xzhXthy38lrbvIM/edit?pli=1#)

**Comment by calerubensteingsa** [comment]
Context from @igorkorenfeld :

This is for a registrant who knows what domain they want and qualify for it

**Comment by calerubensteingsa** [comment]
Know domain is available also

**Comment by calerubensteingsa** [comment]
9/22:

- Moving things over to Figma, working with Michelle

**Comment by calerubensteingsa** [comment]
9/27:

Co work today focused on this, reviewing components of screen and talking about sequence and process. Still have some decisions on what changes (e.g., are we going to try to validate domain as compliant? How much do we want to know before)

**Comment by calerubensteingsa** [comment]
9/29:

- Working on update from co-working, incorporating content and making adjustments
- Added link to in #126 for content - where do we want to have conversations? Igor: Working for me now
- Will carry over to next sprint

**Comment by calerubensteingsa** [comment]
10/3:

- Going to meet and huddle and figure out questions, figure out what to bring back to larger group for round of wireframes
- Goal: Continue iteration

Want to determine what we are/aren't going to include in terms of functionality. Want to get clarity on what we're doing for MVP/first iteration

**Comment by calerubensteingsa** [comment]
10/4:

Meeting today during design huddle

**Comment by calerubensteingsa** [comment]
10/6:

- Yesterday, reconciled the content based on what we decided/discussed in design huddle
- List of questions in notes, some for CISA some for 18F
- Continue async or meet - team will review questions and meet week of 10/10

**Comment by loganmeetsworld** [comment]
10/13
* Iterating based on feedback sessions and conversations in Slack

**Comment by loganmeetsworld** [comment]
Creating a new ticket for follow-on work as v1 is beautiful and has gotten feedback!
