### ISSUE TITLE
Address 'get a .gov domain' button on get.gov (legacy site)

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/getgov#1133]
### Story

As a potential .gov customer or existing customer visiting the legacy get.gov site
I want to understand that I am unable to request a .gov domain during the moratorium (pause on new requests)
so that I don't click the 'get a .gov domain' button thinking I am able to request a domain

### Acceptance Criteria

- [ ] design some possible solutions in Figma for either disabling, hiding, or modifying the button's existing design
- [ ] share final designs in associated dev ticket for implementation

### Additional Context

To review the timeline for the moratorium and "transition experience" between the legacy get.gov site and the beta site view the [roadmap link](https://miro.com/app/board/uXjVMz6Rmi4=/?share_link_id=91482473184)

**Comment by h-m-f-t** [comment]
I have been planning to have this button simply redirect to our forthcoming blog announcing the pause. If you feel like this would be extremely low-effort for you (like one hour) I could support this. 

Changes at the pause are glibly hinted at here https://github.com/cisagov/dotgov-home/issues/158

**Comment by gabydisarli** [comment]
Closing this as a won't do as we've gone in a different direction.
