### ISSUE TITLE
Registrar: UI Dev for DNSSEC requiring ONLY DS Data

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#1148]
### Issue description and context

Implementation based on design output of #1147 

### Acceptance criteria

- [ ] DNSSEC should be changed to match the [figma](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=939-54742&mode=design&t=vm4o8qUrKflG5Mrf-0)
- [ ] update existing tests accordingly

### Links to other issues

blocked by #1147

**Comment by vickyszuchin** [comment]
ACs need to be added. @PaulKuykendall

**Comment by abroddrick** [comment]
added ACs

**Comment by gabydisarli** [comment]
@abroddrick @PaulKuykendall @rachidatecs the flow has been updated at the above Figma link
