### ISSUE TITLE
Invisible "Add another user" link in Domain Registrar

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/getgov#1172]
### Current Behavior

In the prototype registrar, in the "User management" page, the linked text to "Add another user" is invisible. The link is still there, but the text is white/hidden. When you click on the link, the link still works (takes you to the add user page) and the text will show up again.

[I have recorded my steps in recreating the bug.
](https://drive.google.com/file/d/1drvyhRYH0iuux8giF6SyGY725mNgPQzj/view?usp=sharing)

### Expected Behavior

The "Add another user" text should be seen when you first land into the "User management" page.

### Steps to Reproduce

1. Log in the domain registrar
2. Click on "Manage" for one of the domains in the Domains table
3. Navigate to "User management" page

### Environment

This bug occurs in my own account as well as test accounts [bulk login accounts] used for usability testing (https://docs.google.com/spreadsheets/d/148ymzNGYRB_YOFA-lH6ncMCLF2nmVltw2-VIsnmf22g/edit?usp=sharing). 

### Additional Context

[I have recorded my steps in recreating the bug.
](https://drive.google.com/file/d/1drvyhRYH0iuux8giF6SyGY725mNgPQzj/view?usp=sharing)

**Comment by rachidatecs** [comment]
Visible on staging.

Proposed fix in _button.scss, lines 25 to 35:

```
a.usa-button:not(.usa-button--unstyled, .usa-button--outline) {
  text-decoration: none;
  color: color('white');
}

a.usa-button:not(.usa-button--unstyled, .usa-button--outline):visited,
a.usa-button:not(.usa-button--unstyled, .usa-button--outline):hover,
a.usa-button:not(.usa-button--unstyled, .usa-button--outline):focus,
a.usa-button:not(.usa-button--unstyled, .usa-button--outline):active {
  color: color('white');
}
```
