### ISSUE TITLE
Research, document, and implement database migration strategy

### ISSUE THREAD

**Issue by neilmb** [cisagov/getgov#119]
Currently, we don't have a consistent strategy for when and how to run database migrations. In our local docker-compose workflow, we run all of the migrations when the container starts up (https://github.com/cisagov/getgov/blob/main/src/docker-compose.yml#L34). In our cloud.gov workflows, we are also running them on start-up but in a different place (https://github.com/cisagov/getgov/blob/b7200cc9cd584c9a67e4db22a2e185c67e48235c/src/run.sh#L9).  We also have a github workflow to run migrations manually, but only on the staging environment (https://github.com/cisagov/getgov/blob/edc0593859e3bad853df3e777e9f273076ad7630/.github/workflows/migrate.yaml#L30).

Before we go to production, we should have a documented process for how we want to handle database migrations on our production database/application. Run all of them automatically? Run them manually? If so, when and how and by whom?

**Comment by calerubensteingsa** [comment]
Add to Milestone 6

**Comment by calerubensteingsa** [comment]
10/6:

- Draft ADR, reviewed today, more documentation and hopefully done before next week
