### ISSUE TITLE
Having two browsers open to the same domain leads to one showing outdated data

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#1190]
### Current Behavior

Opening both Chrome and safari to the same domain as the same user, and then updating nameservers from 2 to three nameservers on one browser, still showed only 2 nameservers on the other browser. This is because we are caching based on a session, but having two browsers open means that they have diferent caches and the one with 2 nameservers thinks it still has the most up to date info.

### Expected Behavior

Ideally both browsers for a user would show the same info on refresh at least. 

Discuss in **refinement** if we really need this to be the case. This may be a rare usecase that at least lowers the priority on this ticket.

### Steps to Reproduce

1. Open two browsers and sign in with the same user and go to manage domain for both
2. Go to the nameserver page on both browsers
3. add a nameserver on one browser and click save
4. refresh on the other browser
5. notice that the other browser has not updated to show the new nameserver

### Environment

repeated using Chrome and Safari on zanders sandbox.

### Additional Context

This quirk is due to how we have sessions set up and could be fixed by storing the cache in the db (not ideal), or by removing caching completely (which will add some lag). Or can at least be diminished by resetting the cache after a set period of time.

**Comment by PaulKuykendall** [comment]
In refinement, team decided to close "Won't fix." Perhaps we revisit if it becomes a problem.
