### ISSUE TITLE
Implement Login.gov Flow for New and Existing User

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#124]
_Outcome_: 
1. A new user can come to the site, click a "login" button, create a user account and land on a /whoami page. 
2. An existing user can come to the site, click a "login" button, and be redirected to the /whoami page.

- [ ] Backend implementation
- [ ] Frontend implementation
- [ ] oidc wrapper

**Comment by loganmeetsworld** [comment]
Duplicate of #15
