### ISSUE TITLE
OpenID Connect implementation

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#132]
- [x] Bring the django-oidc wrapper into our repository https://github.com/18F/identity-oidc-python-django
- [x] Integrate with OpenID Connect (login.gov)
- [x] Draft an ADR for using login.gov and the trade-offs

**Comment by SSPJ** [comment]
Splitting this from #15 as a discrete amount of work.

**Comment by calerubensteingsa** [comment]
9/22:

Local - can login, can logout. Good to improve error handling, can pass it over to Neil in AM for him to add commits.
