### ISSUE TITLE
Meet and discuss as a group content management options

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#135]
Prepare options to team for creating/managing content in Django app

Discuss needs and identify next steps

Steps:

- [x] Ask CIO/CISO for existing enterprise CMSs
- [ ] Meet as a group to discuss options
- [ ] Make an ADR

**Comment by calerubensteingsa** [comment]
Neil: Seems like a good fit for educational content - we could let Michelle indicate when something is ready.

Michelle: Very low stakes, we're really trying to get a groove on how we put content in there

Seamus: Thinking about how process flow might work for getting content to get to engineering. Mentioned during retro, wondered how much Igor would be interested in prototyping.

Igor: That would be cool, prefer to start out in Mural or Figma - easier to ideate there.

**Comment by calerubensteingsa** [comment]
Agree we don't want content managers to use two different systems for managing content.

**Comment by loganmeetsworld** [comment]
Another content piece to think about is blog/updates

**Comment by calerubensteingsa** [comment]
Hypothesis: Should keep Federalist site that turns it into helpcenter - lives at get.gov, unless there is a WP presence, keeping Federalist site. Seamless b/w registrar and that.

**Comment by calerubensteingsa** [comment]
10/18:

- Set up meeting today, will write up proposal

**Comment by loganmeetsworld** [comment]
I propose that we keep the content for logged out users on a federalist site and fork what is currently at home.dotgov.gov with updates according to policy and product design. I propose that we have this site live at docs.get.gov or help.get.gov and would include all educational content not behind the login screen.

We will discuss this in parking lot tomorrow morning.

**Comment by loganmeetsworld** [comment]
I had originally thought one solution might be to have the “help center” (which is what I’ve been calling all content not part of our application) live at [help.get.gov](http://help.get.gov/) but on second thought I think it’d make more sense to flip it. [get.gov](http://get.gov/) lands you essentially at what [home.dotgov.gov](http://home.dotgov.gov/) is today and keep [get.gov/updates](http://get.gov/updates), [get.gov/help](http://get.gov/help), etc. etc. but when you click “manage my domain” or “get a .gov domain” it takes you to [registrar.get.gov](http://registrar.get.gov/) which is where the django application lives.

**Comment by loganmeetsworld** [comment]
Where we currently stand and can close out the ticket for now: 

We should keep the federalist site but update it or even try to containerize it and add it to cloud.gov (#194), with options in the future to move it into the django app or replace it with a different CMS. For now we plan to keep the django app isolated to only replacing the registrar as it currently stands.
