### ISSUE TITLE
Investigate and document options for role-based access control (RBAC) from the registrant perspective

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#137]

**Comment by calerubensteingsa** [comment]
9/27:

@neilmb next ticket

Seamus: Wondering how much progress we can make on this - need to make RBAC system we can't do that fully until we understand what level of granularity is important

Should we block? No, we can learn a lot by trying to do something like this - come up with a way to put in a group.

**Comment by neilmb** [comment]
Django's permissions are per-model. Each model has four permissions, "delete", "change", "view", "add". These permissions can then be enforced in a `permissions_required` mixin on views. 

This does not seem to match the level of granularity of access that we need where users from an organization should not be able to see anything from a different organization.

**Comment by neilmb** [comment]
We may be best served by a sub-class of `PermissionRequiredMixin` where we can override the `has_permission()` method <https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.mixins.PermissionRequiredMixin.has_permission> to check various attributes of the user (like what organizations they are associated with).

**Comment by neilmb** [comment]
At this point, I don't think that we know enough specifics about the views that we will need for the registrant experience quite yet. I am imagining we will have a `/application/<id>/` detail view. Will that only be accessible to the person who submitted the application or can anyone else from that organization access that object?

If the analysts should have access to all requests, we should be able to use the built-in Django permission system to give them `registrar.view_application` permission.

**Comment by neilmb** [comment]
In a slack discussion, we thought that an `Application` detail view should be viewable by the users who have an email address that matches one of the three contacts listed on that application. So in pseudocode,

```
def has_permission():
    if user.email == application.technical_contact.email or user.email == application.admin_contact.email or user.email == application.system_contact.email:
        return True
    return False
```

**Comment by SSPJ** [comment]
This does seem a sensible direction. One thing I'd like to see decoupled is Users, Groups, Domains, Roles, and Permissions and I'm not entirely clear on how that might work with sub-classing `PermissionRequiredMixin`.

So, for example, **User Bob** works in the mayor's office of Big City, where he is part of **Group Authorizing Authority** for **Domain Big City** (domain in this case meaning in RBAC sense, not in the DNS sense!).  He wants **Permission to view a domain application** and **Permission to sign a domain application** for Big City, which are part of **Role Authorizing Authority**.

He'd go to `/application/1234/` and the system would check, okay, are `1234` and `Bob` in the same ~~domain~~ tenancy (let's figure out a less confusing word for this!)? If so, what roles have the `view_application` permission? Okay, is he a member of any groups that have those roles? He is? Perfect, show him the page...

**Comment by neilmb** [comment]
@SSPJ I think that we will need to implement that clean system in our `has_permisson()` method that checks the possible ways to get permission in some order: Are you in this tenancy? Are you in a group with this permission?

I think that we should design that particular system of access control when we have user stories from the product team that specify the things you mentioned like "as a user in this entity I want to be able to view an application that someone else created so that I can ...."

Currently, the only permission-related user interaction that has been designed is around creating an application and then the people listed on that application should be able to view it.
