### ISSUE TITLE
Equity pause on accessibility

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#138]
Doc for accessibility here: https://docs.google.com/document/d/1yAld85tC_v39jBiA9eKihv9ktzDvhOqwlOirVM2V2js/edit#

Review
- [x] @calerubensteingsa
- [x] @SSPJ 
- [x] @neilmb 
- [ ] @boonerang 
- [x] @loganmeetsworld 
- [ ] @h-m-f-t

**Comment by michelle-rago** [comment]
Equity pause will focus on accessibility. We'll review the [accessibility checklist for teams](https://docs.google.com/document/d/1yAld85tC_v39jBiA9eKihv9ktzDvhOqwlOirVM2V2js/edit#).

**Comment by calerubensteingsa** [comment]
9/27:

- Next equity pause scheduled for 10/21, async follow up for accessibility
- Do we want to schedule another update?

**Comment by calerubensteingsa** [comment]
9/29:

- Useful before retro - input on other sections, everyone wants to make comments.
- Waiting for review, then tickets will created

**Comment by calerubensteingsa** [comment]
10/3:

- Everyone to review

**Comment by calerubensteingsa** [comment]
10/6:

- Waiting on a few reviews, will go through document and tag people in certain areas
- Any tickets in the backlog will be added

**Comment by loganmeetsworld** [comment]
@michelle-rago is going to break out next steps into new tickets
