### ISSUE TITLE
Background dev research for admin experience

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#14]
- [x] Meet with cloud.gov to ask questions about networking for two applications
- [x] ~Draft a diagram of how the backend application might be deployed as two applications, split between the CISA admin and registrant experiences~ N/A, going to develop integrated application for the moment
- [x] Investigate and document options for role-based access control (RBAC) from the CISA admin perspective
    Also see #137 
- [x] ~Investigate and document how both applications might talk to the database~
- [x] Investigate and document how Django Admin might be leveraged in an MVP
- [x] From #277. There is seemingly a bug with FSMField and choices: admin says "Select a valid choice. False is not one of the available choices."
- [x] From #277. Admin does not work with FSMFields if `protected=True`.

~~Do not draft an ADR. There are currently too many unknowns to commit to a decision. The outcome of this ticket will be further tickets (which may include ADRs).~~

See also [this note](https://github.com/cisagov/getgov/pull/248#discussion_r1019578536) on #248 and make sure that testing is part of the A/C of any follow tickets.

**Comment by loganmeetsworld** [comment]
Some questions I've been thinking about:
* Do we have a split between superadmins and admins? 
* How customized does the view for the admin interface need to be?
* Can you put a Django app and Django admin on two different subdomains?

**Comment by loganmeetsworld** [comment]
Next steps for this is a meeting with cloud.gov to discuss our options here and get some questions answered:

* We have one set of routes and interface that might need to go behind a VPN and another that is public. Both need to communicate with the same DB. How should we go about this?
* Admin access vs. registrant access
* What is currently the best option for email notifications?
* What is currently the best option for log storage? / searching?
* We might need a task queue, would CF tasks be sufficient for our use cases or do we need to explore another option?

**Comment by loganmeetsworld** [comment]
Something that might be useful to come out of this ticket as well is an evaluation of what we would need from a CRM, ticketing software, or communications software that would need to be integrated into the analyst/admin side.

**Comment by SSPJ** [comment]
Met with Igor on Friday to review existing features of the Django admin. He suggested a list of items to research for implementation:
- [ ] location of search box / search capabilities
- [ ] ability to run reports
- [ ] ability to export data
- [ ] sorting ability
- [ ] (less important) ability to theme

Next steps are to find potential implementations to those features and make a prototype for Igor to review. The goal is to understand the trade-off in effort to create a new admin interface vs. customizing the existing admin.

That work and the RBAC prototype are the two remaining chucks of work for this ticket.

**Comment by loganmeetsworld** [comment]
Reports that CISA needs: https://github.com/cisagov/getgov/issues/143
