### ISSUE TITLE
Create a method of disabling login required during testing and development

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#141]
⚠ Any method of disabling login creates a "backdoor". ⚠ 

- [ ] document in an ADR security considerations and how risks have been mitigated

**Comment by neilmb** [comment]
this will be important for automated accessibility testing

**Comment by neilmb** [comment]
In Django unit tests, can be accomplished with `force_login`. 

For pa11y, the suggestion in their FAQ https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#how-can-pa11y-log-in-if-my-site-has-a-log-in-form is to use actions to fill a login form and then continue. That could be combined with either a test fixture that includes the test user or a prior call to `manage.py createsuperuser`.

**Comment by calerubensteingsa** [comment]
10/6:

- Working on this, running into some blockers - will work through in engineering huddle
