### ISSUE TITLE
Document reports the program needs for MVP

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#143]
Sample reports are in the [data folder](https://drive.google.com/drive/folders/1qJEXbX8ToviFqhCFKRWKMVz0h-gbePOz) 

Reports in the current system
- Unassigned requests
- Eligibility verification pending
- Domain naming conventions verification pending
- Domain names with naming exception
- Letter pending
- Contact verification pending
- Expired
- Pending CISA approval
- _Domain+ Dump_ https://github.com/cisagov/dotgov-data/blob/main/current-full.csv

.gov domain reporting
- Domain type
- Domain status
- Authorizing agency
- City/state
- Domain Functions
- Domain Redirections
- .GOV Domains Redirections
- Non-.GOV Domains Receiving Redirects From A .GOV Domain
- WWW Hosting Analysis
- Web Servers Hosting .GOV Domains By Country
- Top Hosting Providers
- N-Level Hosts Discovered By Agency & Domain
- Traffic Analysis
- Top Requested .GOV Domains By DNS Traffic
- Top Traffic Gaining .GOV Sites
- Top Traffic Losing .GOV Sites
- .GOV DNS Traffic By Country Of Origin
- Web Site Feature Functionality
- Restricted Crawler User Agents
- .GOV DNSSEC Status |

**Comment by SSPJ** [comment]
Two additional reports which might be useful, if they do not already exist (based on today's meeting to review the dotgov inbox):
* "domains, sorted by domain contact login recency"
* "exceptions granted, by category and frequency"

**Comment by loganmeetsworld** [comment]
@michelle-rago what is the outcome desired for this ticket? Can we document these reports somewhere or is there another element for which we should keep the ticket open?

**Comment by michelle-rago** [comment]
I think we need to work with @h-m-f-t to figure out what CISA needs. I just included reports that currently exist for documentation purposes. I don't think these are meeting CISA's reporting needs.

**Comment by michelle-rago** [comment]
New requirements mention retiring unused domains. We'll need to report these.

**Comment by kitsushadow** [comment]
@h-m-f-t  asking to confirm that there are some reports required for MVP

**Comment by rachidatecs** [comment]
Report 1 example: https://github.com/cisagov/dotgov-data/blob/main/current-full.csv
Report 1 example https://github.com/cisagov/dotgov-data/blob/main/.github/workflows/flat.yml

**Comment by h-m-f-t** [comment]
* current-{[federal](https://domains.dotgov.gov/dotgov-web/publicreports/current-federal), [full](https://domains.dotgov.gov/dotgov-web/publicreports/current-full)} – all .gov domains with metadata. These reports are published online, which we then [grab](https://github.com/cisagov/dotgov-data/blob/main/.github/workflows/flat.yml) to do git scraping.
* Domains by type report
* ...

**Comment by h-m-f-t** [comment]
Reports! They've been documented.
