### ISSUE TITLE
Conversational design exercise - due 10/5

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#151]
Team completes the conversational design exercise

Background: We’ve talked about the people involved on the path to .gov and the kinds of support we’d like users to have. These madlibs are designed to surface the qualities and values we want our product to have. The results will help us build a human-centered product.

Who will do this: This is open to everyone on the team. 
[@cameron](https://gsa-tts.slack.com/team/U03F05DQCRG)
 if you’d like others from CISA to participate that would be great. We can discuss options for getting their input.
How to do this: We each have our own [madlib areas in this Mural](https://app.mural.co/t/gsa6/m/gsa6/1663353098433/e4b84562d04b9151aca8da8bedd1b6d14ebaa29e?sender=michellerago0372). Hop in the Mural to get started. If you would prefer to give your input [in this Google form](https://forms.gle/Lw2vTUeXCQ3GNVhb6) you can do that too. If you have questions or would like to work on this together, let me know.

Deadline: Please add your input before COB on Wednesday, Oct. 5.
Important to note: We want to make sure we’re aligned with Cameron and other CISA stakeholders. While 18F-ers will complete these exercises, we’ll be guided by CISA’s thinking.

**Comment by calerubensteingsa** [comment]
10/4:

- Reup in thread

**Comment by calerubensteingsa** [comment]
10/6:

- Mostly completed, wait until everyone has input, then figure out way to bring it together and explore responses - see how alike they are
- Come up with a way to settle on input, see if we want to that async or see if we want to meet to reconcile

**Comment by michelle-rago** [comment]
[Results of the conversational design exercise](https://docs.google.com/document/d/1czEQIxG05KuWQfggLZC8WVKfDDYtJ8BWSFtOKfD85FA/edit#)

**Comment by loganmeetsworld** [comment]
Completed exercise as team, synthesize in #166
