### ISSUE TITLE
Investigate notification/email service providers

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#16]
- [ ] Investigate and document what other 18F teams have done
- [ ] Gather information on what we would need in order to replicate success stories

**Comment by neilmb** [comment]
https://github.com/GSA/datagov-brokerpak-smtp exists for brokering AWS SES into cloud.gov.

**Comment by michelle-rago** [comment]
[Slack Channel for the “Government Notification Service” 10x project](https://app.slack.com/client/T025AQGAN/C0107UC0W1M)

**Comment by loganmeetsworld** [comment]
Rolling this into investigations into existing enterprise software.
