### ISSUE TITLE
Synthesize Conversational design outcomes document

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#166]
- [x] Review document with team at Design Huddle 10/18
- [x] @h-m-f-t to decide if he wants anyone at CISA to participate (maybe analysts?)
- [x] Determine if we'll get more feedback from CISA, decide how to proceed

**Comment by calerubensteingsa** [comment]
Cameron has two people in mind, one said yes and never responded
Trevor would be good access point as well

**Comment by calerubensteingsa** [comment]
10/25:

- Next step, figure out if anyone from CISA should be involved
- Could come up with plan for that, if not we can include findings in various places
- Have a place to refer to it, make sure we're aligned with those value
- Asked XYZ if they would be willing to do this activity, need to follow up
- Maybe analysts? Can send them the form or a Google doc

**Comment by h-m-f-t** [comment]
Shared the Google Form in my team channel and asked for analyst feedback.

**Comment by calerubensteingsa** [comment]
11/3 - still pending feedback, will close by end of sprint if waiting feedback
