### ISSUE TITLE
Setup pages for sidebar sections

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#174]
- [x] Set up sidebar sections for registrant form utilizing USWDS
~- [ ] Add mechanism for locking future pages~

**Comment by calerubensteingsa** [comment]
10/20:

- Posted screenchat in channel, uses multiple forms, loops through forms and makes a sidebar out of them
- Dev continue to chat through those

**Comment by loganmeetsworld** [comment]
In review #197

**Comment by calerubensteingsa** [comment]
10/25:

- Eng working on PR review, more TO DOs
- Likely 10/26 before revised

**Comment by calerubensteingsa** [comment]
10/27:

- Close, had reviews - one more thing to discuss
