### ISSUE TITLE
Develop accessibility/usability testing options for our team

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#178]
This came out of the [accessibility-focused equity pause](https://docs.google.com/document/d/1yAld85tC_v39jBiA9eKihv9ktzDvhOqwlOirVM2V2js/edit#).

**Comment by boonerang** [comment]
Create basic scenarios for usability testing of a common site. Likely to use an existing site with a simple task, all team members can participate as moderators and observers. We can recruit from within 18F do it over two days.

**Comment by calerubensteingsa** [comment]
Option 1: Create the test, do so ourselves, go through standard scenario - go through a standard test - result could be yes and we schedule
Option 2: Looking to see if training, but doesn't appear to be any

**Comment by boonerang** [comment]
It doesn't lool like we offer an in-house training option. So we're going with internal reading and training.
We'll collect and discuss resources [like the in house guides](https://accessibility.digital.gov/) and [articles like this.](https://medium.com/inclusive-research/preparing-for-inclusive-research-with-people-with-disabilities-228ce2f8cb2e)

**Comment by boonerang** [comment]
Also, when we move into testing we could consider working with a group like [Knowbility to connect with testers who can put our work through the paces](https://knowbility.org/services/usability-testing). (I've worked with them in the past and the were great.)

**Comment by calerubensteingsa** [comment]
10/31:

Go with internal reading, do testing ourselves
