### ISSUE TITLE
Read up on cognitive and learning disabilities accessibility

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#179]
Read up on the Cognitive and Learning Disabilities Accessibility Task Force objectives:
- [Making Content Usable for People with Cognitive and Learning Disabilities](https://www.w3.org/TR/coga-usable) 
- [Testable Statements for Each Pattern - Cognitive Accessibility Task Force (COGA)](https://www.w3.org/WAI/GL/task-forces/coga/wiki/Testable_Statements_for_Each_Pattern)

This came out of the [accessibility-focused equity pause](https://docs.google.com/document/d/1yAld85tC_v39jBiA9eKihv9ktzDvhOqwlOirVM2V2js/edit#).

- [ ] Create items/research questions to either investigate or discuss

**Comment by calerubensteingsa** [comment]
Michelle had linked to some documentation, review that

**Comment by calerubensteingsa** [comment]
10/26:

- @michelle-rago started, a lot there - one example for implications, whether we should estimate for amount of time form might take

**Comment by calerubensteingsa** [comment]
10/27:

- Continuing to read through
