### ISSUE TITLE
Review role-based accessibility site

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#180]
For the team: review this role-based accessibility site to explore how each of us can contribute to accessibility 
 https://accessibility.digital.gov/. 

This came out of the [accessibility-focused equity pause](https://docs.google.com/document/d/1yAld85tC_v39jBiA9eKihv9ktzDvhOqwlOirVM2V2js/edit#).

- [x] [Product](https://accessibility.digital.gov/product/getting-started/) @calerubensteingsa 
- [x] [Content](https://accessibility.digital.gov/content-design/getting-started/) @michelle-rago 
- [x] [UX](https://accessibility.digital.gov/ux/getting-started/) @boonerang 
- [x] [Visual design](https://accessibility.digital.gov/visual-design/getting-started/) @igorkorenfeld 
- [x] [Frontend](https://accessibility.digital.gov/front-end/getting-started/) @loganmeetsworld
- [x] [Frontend](https://accessibility.digital.gov/front-end/getting-started/) @neilmb 
- [x] [Frontend](https://accessibility.digital.gov/front-end/getting-started/) @SSPJ 
- [x] [Product](https://accessibility.digital.gov/front-end/getting-started/) @h-m-f-t

**Comment by michelle-rago** [comment]
Reminder for team: suggest courses or further reading for team members on accessibility.

**Comment by boonerang** [comment]
[Good article here with lots of details on testing. ](https://medium.com/inclusive-research/preparing-for-inclusive-research-with-people-with-disabilities-228ce2f8cb2e)
