### ISSUE TITLE
Educational content - Before you request page

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#181]
- [x] Draft content for [Before you request a domain](https://docs.google.com/document/d/1_P7W-kuBflak7opYK_M5wjYs3xJIFKE64hbBxqX9Mvg/edit#)
- [x] @loganmeetsworld to review content by COB on 11/14
- [ ] @h-m-f-t to review content by COB on 12/7
- [ ] Edit as needed
- [ ] Indicate when content is final

**Comment by calerubensteingsa** [comment]
11/3 - same as above

**Comment by loganmeetsworld** [comment]
I've done a first pass at reviewing but we probably need some back and forth. Overall I think content is really great but have some questions about placement of information in the flow.
