### ISSUE TITLE
Create forms and flows for a customer panel

### ISSUE THREAD

**Issue by boonerang** [cisagov/getgov#184]
Using touchpoints we'll create a post-registration form to ask if people would like to be involved in future testing and iteration on the registrar. ([Doc explaining the concept](https://docs.google.com/document/d/1cIpGhgg2UlWuDk8VLhXHFlB_8KWOpCVcBRWtoOz7kJw/edit).)

- [x] Create and test form in Touchpoints
- [x] Understand how data is store in Touchpoints
- [ ] Copy for email
- [ ] Test a flow with signing up and what sort of segmentation (if any) we can apply

**Comment by calerubensteingsa** [comment]
10/25:

- Form up and tested, see how data is used
- Afternoon, chat about PRA, guidelines for what we want to capture
- Information on what we need to submit
- Get it live and test
