### ISSUE TITLE
External recruiting sources and forms

### ISSUE THREAD

**Issue by boonerang** [cisagov/getgov#185]
Gather a list of sources we can recruit from for future testing and a form within Touchpoints we can share to gather the participants prior to research.

- [x] Create form in Touchpoints (what sort of segmentation, if any, can we add).
- [x] Collect sources for recruiting (Town Clerk associations, state level groups, civic tech groups, etc.)

**Comment by calerubensteingsa** [comment]
10/18: Dropped into channel for other places for report, where can we bring in people from other sources

**Comment by calerubensteingsa** [comment]
10/20:

Going to be part of coworking discussion

**Comment by calerubensteingsa** [comment]
10/25:

- Talking about that today in docs, getting a consensus round - figure out best way to do that

**Comment by boonerang** [comment]
We are going to use a variation of the current Exchange form CISA is using. We may still use Touchpoints but versioning the current form is the path of least resistance.
