### ISSUE TITLE
Wireframe for new domain request form for new registrants (V2)

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#188]
Continue work from #113 on a low-fidelity wireframe of the new domain request form for new registrants. Incorporating rest of the feedback and the new content.

_Outcome_: V2 wireframe ready for implementation of domain request views in cloud.gov environments.

Remaining tasks:
- [x] Adjusting the contacts page (admin/tech -> non-role specific)
- [x] Adjusting the domain name selection page and flow
- [x] Inputting the content from #177 
- [x] Seek feedback on v2 for further adjustments

**Comment by calerubensteingsa** [comment]
10/18:

Continue to work on it, make some updates on the way things link to each other
Waiting on content from #177

**Comment by calerubensteingsa** [comment]
10/25:

- Made updates, discuss during design huddle
- Any other changes for content can bring it in, pretty good point now - pending discussions

**Comment by calerubensteingsa** [comment]
10/27:

- Waiting for team review
