### ISSUE TITLE
Inquire about CISA style guides

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#189]
Ask @h-m-f-t about style guides to see what settings we should use for USWDS in our application. Prerequisite for pulling in USWDS in wireframe from request flow for new registrants in #188.

Next step is to figure out how to reflect those styles in wireframe.

**Comment by h-m-f-t** [comment]
:ohno:

**Comment by h-m-f-t** [comment]
I'm double-checking it's the latest but here's the CISA style guide I have: https://drive.google.com/file/d/1EMfuLWlJF7k21BcIAtenRelfX9yaWFqS/view?usp=sharing
