### ISSUE TITLE
Register a new domain for the registrar (get.gov)

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#193]
# Background

We are seeking a new domain to be the landing site for the registrar (get.gov) and related content about the DOTGOV Act and dotgov program. This would replace home.dotgov.gov and related dotgov.gov sites upon launch. 

The motivation behind the change is to disambiguate the site from the program, the law, and the process of obtaining a .gov domain. 

# Known steps

We need to go through both CISA and DHS CIO offices and then seek approval in tandem with OMB.

**Comment by calerubensteingsa** [comment]
10/20:

Approved, in route to DHS CIO

**Comment by calerubensteingsa** [comment]
10/26:

- Email snoozed until tomorrow, current at CISA's external affairs, has to be routed to DHS external affairs - have to go to XYZ. Still in progress.
- Can close ticket out if we've fulfilled part we have to do

**Comment by loganmeetsworld** [comment]
We have responded to several emails with the external affairs office at CISA and are awaiting reply.

**Comment by calerubensteingsa** [comment]
Followed up 1/9, confident we will get the desired URL. Have senior support. At office since December 14th.
