### ISSUE TITLE
Discovery: Consider how to let authenticated users request support

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#1930]
### Issue description

Problem/Opportunity: Inbound messages, like from the Contact Us form, currently originate from the get.gov site which is public. The email address is simply entered into the form and is NOT verified. Our analysts need to verify that the email is legitimate and is controlled by the person making the request. This can take a significant amount of time.

Solution: Provide a mechanism for authenticated users to submit a contact form so that we know who they are based on their login, i.e. users that are logged in thru Login.gov. This would exist on manage.get.gov. 

Benefits: Time saving and Trust of request

The get.gov public site should:
- direct people to Login for any questions about existing domains or domain requests.
- allow for general questions from the public, but not anything specific to an existing item.

### Acceptance criteria

Discovery
- [x] Requirements are determined, and decisions made
- [x] Design tickets created

### Additional context

([Slack chat](https://cisa-corp.slack.com/archives/C066ZBWFLRW/p1710517144022869?thread_ts=1710515368.014639&cid=C066ZBWFLRW))
In general, we will prefer to interact with users "in-platform," for a few reasons:
- we know who we are interacting with
- we record a log of actions/communications taken.
- we can easily (eventually) interact with users in-platform
- the message text may be stored in our database, so that it can be reviewed over time. (See ARIN example)

### Links to other issues

Related to cisagov/get.gov#288 (Discovery to reduce inbound helpdesk emails/burden)
Blocks cisagov/manage.get.gov#2011 (new process for authenticated users)
Blocks cisagov/manage.get.gov#2099 (new process for unauthenticated users)

**Comment by vickyszuchin** [comment]
This ticket was moved to sprint 44 in the "In review" status.
