### ISSUE TITLE
Seek AWS access for external non-cloud.gov services needed in the registrar

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#202]
# Background

We have several pieces of functionality we need to serve all user stories in the registrar. The main ones we have identified are **a notifications provider** and a **software queuing system**. Both of these services could be provided as external services in an AWS environment through SES and SQS.

**Comment by loganmeetsworld** [comment]
This is in progress and steps for setting this up can be tracked in a new ticket
