### ISSUE TITLE
Fix OWASP failing

### ISSUE THREAD

**Issue by allly-b** [cisagov/getgov#2050]
### Issue description

Last week Owasp began failing on every PR, at the same point in time OWASP did an update. Given the error is a format error (see any of the error logs) it seems reasonable we just need to rollback the version of owasp being used. if this doesn't work additional troubleshooting is needed to figure out why it's failing and how to fix (though time box it to 2 focused days of work).

### Acceptance criteria

- [x] OWASP is no longer failing on PRs

(note no test is required, just make a PR with your fix and if OWASP doesn't fail then we should assume the above AC is met

### Additional context

I believe the version for owasp is set in docker-compose.yml and at the line "image: owasp/zap2docker-stable" which is by default the latest (and thus breaking change). We then just need to change this to indicate the last version prior to this update. 
However, at this same time there were breaking version updates from audit log and django fsm, if somehow our app when running owasp is getting the newest dependency versions that could also explain this completely failing in which case we would need to update the dependency setup when running owasp. I do think this is less likely but the timing is so close it's worth mentioning.

**Comment by abroddrick** [comment]
@trevorbryant-cisa I unassigned myself just because I will be gone for a week, and don't want to block on this one. I think reverting the OWASP package dependency to a lower level may be a good one for @zandercymatics to help on. Tagging as maybe you two could pair when he finishes his already complicated ticket.

**Comment by trevorbryant-cisa** [comment]
Sounds good!
