### ISSUE TITLE
Workshop: Pre-mortem, Project Risks / ROAM exercise

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#21]
- [x] Schedule time to do this as a product team (if possible)
- [x] Schedule time with Executive Sponsor (late week of 5/29)
- [x] Review potential risks
- [ ] Align on mitigation strategy for each risk
- [x] Assign owner if needed
- [x] Document risks in product strategy
- [ ] Set up risk review every 6 weeks?

**Comment by colinmurphy01** [comment]
Make a call to include this in this sprint 3 or sprint 4 by 08/12

**Comment by colinmurphy01** [comment]
Review risk register from Design Studio

**Comment by colinmurphy01** [comment]
Prioritized 30 min for Sprint 3 - list out risks, get explicit risk mitigation and ownership strategy.

**Comment by colinmurphy01** [comment]
Next steps: 

- @calerubensteingsa will export sheet into shareable doc and send to @h-m-f-t 
- @h-m-f-t to take first pass
- @calerubensteingsa will work with @h-m-f-t to identify meeting time with Executive lead
- Regroup on which risks we should present to Executive lead

**Comment by loganmeetsworld** [comment]
@calerubensteingsa what is the current status of this?

**Comment by calerubensteingsa** [comment]
I believe still In Progress. @h-m-f-t  is reviewing, but I will sync with him to see if we should regroup on it next week.

**Comment by h-m-f-t** [comment]
I'll have the risk review _reviewed_ before retro. I've also chatted with the executive sponsor, who said they'd happily participate in the next review.

**Comment by loganmeetsworld** [comment]
Closing this out as the last task here should be to review with senior executives and set reoccuring meeting, which we have scheduled.
