### ISSUE TITLE
Prepare User Testing Materials for Wireframes for New Registrants

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#210]
- [ ] Writing intro and outro text, existing and potential registrants
- [ ] Draft plan for goals and what participants will be shown
- [ ] Test flows internally to confirm external participants can see/use the prototype
- [ ] Write scripts/test materials
- [ ] Conduct user testing of wireframes for new registrant domain submission

**Comment by boonerang** [comment]
[Draft plan started here,](https://docs.google.com/document/d/1wi6hxG432RKZv7dbDu6xuXjfRad-IizdmX224LBzd98/edit?usp=sharing) will discuss and add more details in coming days.

**Comment by calerubensteingsa** [comment]
11/10:

- Look at wireframes, get people through it - will create script from that
