### ISSUE TITLE
Identify participants for wireframe feedback for new registrants

### ISSUE THREAD

**Issue by boonerang** [cisagov/getgov#214]
- [x] Decide on email outreach or get Touchpoints form in place
- [x] Update past outreach letter
- [x] Set timeframe and cadence 
- [ ] Create tracking sheet and start scheduling sessions
- [ ] Outreach to CISA reps
- [ ] Go through and identify participants for recent registrants/filter by city/identify to recruit after holiday

**Comment by boonerang** [comment]
Using existing CISA form, waiting to see what response rate looks like!

**Comment by calerubensteingsa** [comment]
Expanding pool per: https://www.google.com/calendar/event?eid=NGxsMzFlaGwzZG0zOGpsN2dlNTZ1NnFwcDYgbG9nYW4ubWNkb25hbGRAZ3NhLmdvdg

**Comment by calerubensteingsa** [comment]
- Reach out to regional reps to get names
