### ISSUE TITLE
Research django-audit and how audits of models like Application work

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#218]
_Outcome_: Select a process for auditing events in our Django application, investigate django-audit 

- [ ] Write up ADR

# Background

It is a good idea to have traditional domain models like “Application” and some way to tie LoginUser to Application. Whereas the registry will be complete source of truth for Domains, we will have to track and keep the truth for Applications.

There are two areas event sourcing or even tracking could bring benefit - Application (just a series of events) and changes to users permissions/roles/domains/etc. We believe this will be best modeled in the db with traditional modeling for it and decouple the audit logs - a separate table that is an event source but it not the model.

The benefits to this approach: 
- For analysts working on an application, see a history of how and when and who has changed the state of that application 
- The detail page for a domain application would have a table for past changes - SELECT FROM events WHERE app.id == app.id

**Comment by SSPJ** [comment]
https://github.com/jazzband/django-fsm-log

**Comment by calerubensteingsa** [comment]
11/8:

- Found library, taking some time to see how we may query the table

**Comment by calerubensteingsa** [comment]
PR 11/10
