### ISSUE TITLE
Research finite state machines as a way to model changes to model state

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#219]
_Outcome_: @neilmb will deliver a presentation based on a previous discussed example of Application statuses to the next engineering huddle. 

Explore FSM libraries that are compatible with Python and Django and gather information on implementation using our example. 

# Background

We have had some interest in exploring FSM for our data modeling. While there is some reason to be skeptical (possible added complexity for a simple case) we do have finite states that need logic to support them. 

The idea of an FSM is that the system has a rigorously defined model of what changes are allowed and can reject changes that would cause inconsistent state i.e. an analyst sets a domain application from submitted to approved without going through investigating stage. 

The hope for the state machine approach is that it condenses and localizes the place we document the conditions for those state changes.

We decided to focus on one case - an Application moving pending to submitted - and see if any available libraries or patterns would work well for us. This is also connected to #220 as we want to thoroughly understand the states Application will move through.

**Comment by calerubensteingsa** [comment]
11/3:

Working on 219, demo during engineering huddle
Take follow on next week
