### ISSUE TITLE
Send recruiting emails to first round of possible participants

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#229]
- [ ] Send recruiting emails to first round of possible participants
- We'll want to send the first round of email from CISA addresses

**Comment by loganmeetsworld** [comment]
Covered by other things

**Comment by boonerang** [comment]
[Copy for outreach emails here](https://docs.google.com/document/d/1NJuAsbkxTl7jLwxkDyf24sIywA-TyJaUq8FrzZI9GX0/edit#heading=h.ux113m1or1v8). This can likely be deprecated/archived though.
