### ISSUE TITLE
Implement frontend views from wireframes in the Django application

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#231]
_Outcome_: Content and proposed views from #190 for the new registrant form are implemented in the Django application. 

This does not require functionality to manipulate Application state which requires #221 and #222 

Views to implement:
- [x] Type of organization  
- [x] Organization name and mailing address
- [x] Authorizing official
- [x] Website for your organization
- [x] .gov domain
- [x] Purpose of your domain
- [x] Contacts for your domain
- [x] Other contacts for your domain
- [x] Security email for public use
- [x] Anything else we should know?
- [x] Requirements for registration and operation of .gov domains
- [x] Review and submit your domain request

- [ ] Testing

**Comment by calerubensteingsa** [comment]
11/3 - it make sense to break out into per-view ticket? Joining engineering huddle

**Comment by calerubensteingsa** [comment]
11/8 - updating base form as well

**Comment by loganmeetsworld** [comment]
Implemented in #257, which is in review

**Comment by calerubensteingsa** [comment]
11/17:

- Responding to PRs
