### ISSUE TITLE
Spike: explore moving Cloud.gov Pages site to non-jekyll static site generator

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#232]
- [ ] Figure out research guides and methods group has done
- [x] Spike on moving the site to 11ty or similar
- [x] Report out findings

**Comment by calerubensteingsa** [comment]
11/10:

- Spend some time with educational content
- Do we keep same homepage, do we wrap Django app with CMS we use?
- CMS is just educational content - sticking with original decision for CMS as part of site

**Comment by loganmeetsworld** [comment]
I spiked on this with https://github.com/loganmeetsworld/11ty-gov. I think we should stick with Jekyll for now. There is considerable work to make the transition to 11ty.
