### ISSUE TITLE
Conduct New Registrant Wireframe User Feedback Sessions

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#238]
- [x] #239

**Comment by boonerang** [comment]
Research finished, two major outputs

- [.gov Initial Prototype Feedback](https://docs.google.com/document/d/1M5AN2jY6m1T73dZ9Rw6qSUc37YZ8udEA_rsWfoVVs9E/edit#heading=h.jmjn81mtfaop)
- [.gov Prototype Order & Flow Update](https://docs.google.com/document/d/1wb6_JUGVmSYeTvGrcH2GxWv81xUDdmbtz19XbXyw-cI/edit)
