### ISSUE TITLE
Spike: Identify Content Needed for educational regarding login

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#242]
- [x] Research what other login.gov customers are doing for identify proofing
- [x] Prioritize login content for new users (as opposed to migration or process for users with existing accounts)
- [x] Identify CISA content needed to educate registrants on login.gov process and where login.gov has content
- [x] [Draft content](https://docs.google.com/document/d/1bvWPa2i0mrhDR4iNa0cBErMfSJ4RzUHpQ4Zz_YdPzCc/edit#)
- [ ] Create ticket(s) for future content identified or investigation needed

**Comment by calerubensteingsa** [comment]
12/22:

- Do we want to send people to login.gov page or a custom page?

**Comment by michelle-rago** [comment]
Draft content https://docs.google.com/document/d/1bvWPa2i0mrhDR4iNa0cBErMfSJ4RzUHpQ4Zz_YdPzCc/edit#

**Comment by calerubensteingsa** [comment]
Will close by end of sprint

**Comment by calerubensteingsa** [comment]
1/5:

- Discuss during design huddle
