### ISSUE TITLE
Develop Recruiting Materials

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#254]
- [x] Outreach to CISA reps
- [x] Discuss prioritize segments (based on past conversations and post-election timelines)
- [x] Go through and identify participants for recent registrants/filter by city/identify to recruit after holiday

**Comment by calerubensteingsa** [comment]
11/17:

- Met with Cameron, sketched out plan for chatting with CISA reps
- Had a meeting with IOD, help manage and run 10 regions

**Comment by calerubensteingsa** [comment]
11/22:

- Waiting to hear back from Cameron, going to start on outreach after holiday - reach out to 10 regions and identify candidates

**Comment by boonerang** [comment]
- CISA outreach materials are ready, will drop first week in January. [More details here](https://docs.google.com/document/d/1NJuAsbkxTl7jLwxkDyf24sIywA-TyJaUq8FrzZI9GX0/edit#heading=h.ux113m1or1v8).
- Prioritization [discussion notes here](https://docs.google.com/document/d/1okwiioz0i2yDQxmvnpFP_K2spB3wlKJpEEXgaLv0pxk/edit).

**Comment by calerubensteingsa** [comment]
1/3:

- Email ready to send to reps
- Put email into some of groups
- Looking at some internal testing
- Looking at weeks 1/2 of month for recruiting, 4/5 for testing

**Comment by calerubensteingsa** [comment]
1/5:

- Emails sent, got respond
- Seeing if we can bring in internal people

**Comment by boonerang** [comment]
Outreach materials updated with specific details on the study for reps to share, apologies if the team inbox gets hectic over the next few weeks.

**Comment by calerubensteingsa** [comment]
1/12:

- Spent some time talking to DHS people, some paperwork for how to have executives join us

**Comment by boonerang** [comment]
1/13

- Screening call done for one participant 👍 
- Screening call scheduled for 2nd participant
- Email out to schedule 3rd screening

**Comment by calerubensteingsa** [comment]
Next steps:

- Walkthrough of prototype, go through each screen
