### ISSUE TITLE
Update Prototype with Footer and Header

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#259]
See [option A](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FWireframes?page-id=1007%3A4676&node-id=1022%3A4952&viewport=1193%2C-651%2C0.36&scaling=min-zoom&starting-point-node-id=1022%3A4952&show-proto-sidebar=1&hide-ui=1) and implement the footer from home.dotgov.gov.

For reference: https://github.com/cisagov/dotgov-home/blob/main/_includes/footer.html

**Comment by calerubensteingsa** [comment]
11/22:

- WIP, has links but no targets, doesn't have colors or typography
- Next week - Michelle and Igor will sync to finalize

**Comment by michelle-rago** [comment]
Developing footer content here https://docs.google.com/document/d/1pJ80l20F8myYJCu4G9AaBANi1aX8LSyP-UlCGzHq-OU/edit#

**Comment by neilmb** [comment]
Running WIP based on that Google Doc now at getgov-unstable.app.cloud.gov.
