### ISSUE TITLE
Add field validation for all form fields in the domain application request form

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#262]
_Outcome_: Ensure all required fields are required and any validation we want on individual fields is implemented. 

*Requires design work*

We should ensure browser/frontend error handling is correct as well as validation for the state transition to submit. When there is an error on submission, we should give helpful instruction as to how to fix the error.

Should include the URL validation for available, unavailable, and non-compliant URLs

A/C: As a user I want timely and clear response when I input something that is not allowed on submission.

**Comment by SSPJ** [comment]
Team engineering huddle talked about this today. [Notes](https://docs.google.com/document/d/1sjIuqsqNpHgMYfKieHF88DlBc6GcI3JmljKgrDJvUMg/edit#bookmark=id.6dwz6xvklmua) 🔒 are here.

Discussion focused on the backend behavior, the use of Save vs Next, Django messaging. TBD is how frontend validation will work or be stylized.

**Comment by loganmeetsworld** [comment]
Adding context from #292 here since I believe these are the same: 

Validation Issues found in QA

* No validation on the state dropdown (when a user doesn't include a state in an address form, there is no validation it hasn't been selected). For example, no error is shown if somoeone doesn't choose a state on https://getgov-staging.app.cloud.gov/register/organization_contact/
* On https://getgov-staging.app.cloud.gov/register/current_sites/, the field does not validate for a website. A user does not have to put in a ".", or can put in a variety of characters. Expected it would validate against a website structure
* No validation or error message if user doesn't confirm reading terms and conditions? https://getgov-staging.app.cloud.gov/register/requirements/
* Validation for email field (example, on https://getgov-staging.app.cloud.gov/register/authorizing_official/) requires a @ symbol and text after the @ symbol, but does not accept an email like cale@cale in that it does not allow user to proceed to next step. However it provides no error messaging

**Comment by loganmeetsworld** [comment]
Question: Does this include implementing a messaging system?

**Comment by neilmb** [comment]
@loganmeetsworld Yes, I have put form field error handling into the templates to do this. They were already there, we just weren't including the right things in our templates. (Future selves: form errors are in `form.errors`, separate from `messages`.)

**Comment by neilmb** [comment]
Got on-page state feedback working:

![Image](https://user-images.githubusercontent.com/443389/207098732-55dc1d8f-d770-4262-bc42-1822348894db.png)

**Comment by calerubensteingsa** [comment]
@igorkorenfeld @michelle-rago to review, bunch of error messages in PR, figure out how we want to get the right text - meeting to go over what workflow may be in Github
