### ISSUE TITLE
Update Domain Application Form Prototype with Style A Designs

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#265]

**Comment by calerubensteingsa** [comment]
11/23 - found an issue with padding for "locked" steps because they are not links: https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1669222631868799

**Comment by calerubensteingsa** [comment]
12/6:

- Make changes based on PR feedback

**Comment by loganmeetsworld** [comment]
PR open #298
