### ISSUE TITLE
Bulk load fake login accounts for testing and create fixtures for those emails in our application

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#266]
_Updating this based on the below comment_

>If that is the case, the easiest method would likely be to take login.gov up on their [bulk loading offer](https://gsa-tts.slack.com/archives/CG64NU5C7/p1668698305409899) 🔒 with emails like me+testuser1@, me+testuser2@ and then make use of our [fixtures](https://github.com/cisagov/getgov/tree/main/src/registrar/fixtures) to automatically recreate the corresponding user accounts, domains, applications, etc in a clean, fresh state each time the app is deployed. Testers would then be given the username and password for the account specific to what we are currently asking them to test.

- [x] Ask Login partners to load ~10 fake emails with identity verification into the sandbox for us
- [ ] Create fixtures for accounts for those emails 
- [ ] Test in a video meeting that it is easy to walk participants through the 2FA step

**Comment by loganmeetsworld** [comment]
Thanks @SSPJ! I will update the ticket a bit but we're deprioritizing this for a sprint or two until we have formulated a testing plan. I agree with the bulk loading being the easiest (and imo preferable path forward).

**Comment by loganmeetsworld** [comment]
I chatted with some folks at Login - they recommended that when we have only a handful of accounts for testing to hand-make them using the  “plus trick” (e.g. [your.email+whatever@gsa.gov](mailto:your.email+whatever@gsa.gov)) - which I could do on a new google group. 

Also, downloading the list of MFA backup codes and just giving those to the testing participants. I can do this and make a doc tracking those accounts / what they’re for and a list of backup codes to draw from. Then we can add fixtures for personas for the various users. Assigning to myself.

**Comment by calerubensteingsa** [comment]
List of accounts, PW, and backup codes: https://docs.google.com/spreadsheets/d/1QkK4oXhc5Cum37N9v9_vcEUePmgpAkF_h66qyl6wJ3Y/edit?usp=sharing

**Comment by boonerang** [comment]
Wicked!

[I've started a doc for details about the scenarios for each account in the research folder](https://docs.google.com/document/d/1fSwlHtOGhqnRwzNZmHpygsJag45Nnt-v8KkTr_eqYLw/edit?usp=sharing). We can use this for noting the scenarios, details for what data needs to be pre-loaded, etc.
