### ISSUE TITLE
Secure a FISMA id for our system boundary

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#274]
# Background

One of the first steps in beginning the ATO process is to get in the system of record with a FISMA id in CSAM (a DOJ hosted service for tracking ATO). We are currently working through the steps required for this.

**Comment by loganmeetsworld** [comment]
Current work being done 11/16 by the team to support this: #275

**Comment by calerubensteingsa** [comment]
11/28 - comes after Inventory form
