### ISSUE TITLE
Add current state systems diagrams for ATO

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#275]
During planning this week @trevorbryant-cisa mentioned it would be helpful to have current systems diagrams for ATO and boundary definition purposes. 

- [x] Software Development Lifecycle (SDLC) diagram showing deployment process
- [ ] Overall boundary diagram with external services shown

**Comment by loganmeetsworld** [comment]
Branch in progress with this work here: https://github.com/cisagov/getgov/tree/lmm/system-diagram

**Comment by calerubensteingsa** [comment]
Another draft for integrating with external systems
