### ISSUE TITLE
Seek approval for the domain registrant form under PRA

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#276]
# Background

Since our form is open to the public and specifically SLTT folks, we must seek PRA approval to assess the impact of our form. There are a series of steps we will have to take moving forward: 

- [x]  Initiate PRA Process
- [x] **We are here!** PRA Package Development
    - [x] Finalize the data we are seeking from the form
    - [x] @calerubensteingsa -We draft the 60-day FRN ([link)](https://docs.google.com/document/d/1rkj3TNigteflI22GFFYqHMs2O_XCnRa6/edit?usp=sharing&ouid=112603364296540269986&rtpof=true&sd=true)
        - [x]  @loganmeetsworld review
        - [x] @h-m-f-t review

    - [x] @calerubensteingsa - We draft the support statement document ([link](https://docs.google.com/document/d/1QGlQ06wZNrFoX5uVI7qWMMfkMrtaOmzb/edit?usp=sharing&ouid=112603364296540269986&rtpof=true&sd=true))
        - [x]  @loganmeetsworld review
        - [x] @h-m-f-t review
    - [x] We prepare the instrument
- [x] @h-m-f-t Reach out to PTA to get relevant privacy documents
- [x] Re-edit the PRA Package development
- [x] 60-Day FRN and Package Preparation
    - [x] Finalize package preparation for approvals
    - [x] OCIO PRA Officer emails the PRA documents to the Privacy Office
    - [x] Office of the Chief Economist (OCE) and the Office of the Chief Counsel (OCC PRA) clear documents
    - [x] 60-day FRN sent to OCC Regulatory for a final review
    - [x] OCIO PRA Officer obtains the CIO’s signature
- [x] 60-Day FRN Finalization & Public Comment
    - [x] Clear the initial package
    - [x] OCIO PRA Officer requests a Federal Docket Number by filling out a docket request form 
    - [x] OCIO PRA Officer sends document to Regulatory Law Division
    - [x] OCIO PRA Officer adds the docket number into the 60-day FRN 
    - [x] OCIO PRA Officer sends the final 60-day FRN to the CIO for signature
    - [x] Final document with signature returned to OCC Regulatory so they can make formal request to publish
    - [x] 60 day waiting period
- [x] 60-Day FRN Results:
    - [x] Compile and synthesize public comment
    - [x] Respond to any comment
- [x] 30-Day FRN Preparation
    - [x] We draft a 30-day FRN (responding to any comments)
    - [x] We send finalized 30-day draft FRN to OCC, OCE and the Office of Privacy for review
    - [x] After cleared by the above offices, signed by CIO
    - [x] OCC PRA Officer sends the signed 30-day FRN to OCC Regulatory again to request that the 30-day FRN be published
- [x] 30-Day FRN Results
    - [x] OMB sends 30-day comments to DHS HQ PRA
    - [x] We provide updates to the OCIO PRA Officer.
    - [x] OCIO PRA Officer addresses any comments with the us 
    - [x] OCIO PRA/DHS HQ PRA Sends to OMB through ROCIS (DHS HQ PRA prefers that we request such submission through their DHS Jira Account)
    - [x] Make updates after feedback from OMB/DHS HQ
- [x] To OMB/OIRA - follow up with CISA PRA (CIO)/DHS PRA and colleagues at OMB
- [x] Approval

**Comment by h-m-f-t** [comment]
We started this process on 24 April 2022. Our ICR was approved by OMB yesterday, 3 Oct 2023. Apparently this was fast 😶‍🌫️ 

"The collection .gov Registrar has been approved by OMB/OIRA. When using the collection, please remember to include the [Burden Statement](https://usdhs.sharepoint.com/:w:/s/CISA_OCIO_Intranet/PRA_PROD/Ecm3RYpbOz9Gg2ZnN_FMSm4B5dDTqb5S-N6rc3J6_sTPFg?e=7fKY9o), OMB Control Number (1670-0049), and the expiration date of 10/31/2026."
