### ISSUE TITLE
Django admin: Federal agency page updates

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/getgov#2868]
### Issue description

The federal agency page in django admin needs a few QOL and consistency updates to better reflect our established patterns. More specifically, we should change the "agency" and "federal type" fields.

### Acceptance criteria

- [ ] Update "agency" field to read as "Federal agency" on the Federal Agency page to match other instances of that field.
   - Ensure that this change is also present on the table view.
- [ ] Update the "agency" field to be required
- [ ] Update the "federal_type" field to be required
- [ ] Remove helper text underneath the "Federal agency" field.

### Additional context

Regarding the first A/C: Note that the name on the frontend doesn't always need to match what is on the backend. Please use `verbose_name` rather than renaming the field in the DB.

**Comment by h-m-f-t** [comment]
@zandercymatics would this affect the data in current-full/federal? If so, how?

**Comment by abroddrick** [comment]
I thought we already had double checked that all federal agencies have a branch (aka federal type) associated with them. So there should not be any on stable that are missing it. That said, there could easily be ones that developers made in test sandboxes. 

This should not affect our current full and current federal data and will just require a user to fill in federal agency fully before creating a new fed agency record. 

As for the rename, @zandercymatics we definitely shouldn't rename this field in the db this should just be a visual change using verbose. This follows what we have done for other fields.

**Comment by shahzaib512** [comment]
Hi @zandercymatics, I'd like to contribute to this issue!  
Here’s my proposed plan:  
1. Update the "agency" field label to "Federal agency" using `verbose_name` to ensure it's only a visual change.  
2. Modify the model forms to make "Federal agency" and "federal_type" fields required.  
3. Remove any helper text below the "Federal agency" field.  
4. Verify that the changes reflect in the Django Admin table view.  

Let me know if you have any specific preferences or further recommendations! I'd be happy to start working on this.
