### ISSUE TITLE
Investigate Cloudflare CRUD commands

### ISSUE THREAD

**Issue by allly-b** [cisagov/getgov#2874]
### Issue description

To do DNS hosting, the most basic thing we need to do is CRUD operations with their API for a given domain. We should document these clearly and investigate the architectural and programmatic impacts. 

### Acceptance criteria

- [ ] Try the CRUD commands in command line
- [ ] Document the CRUD commands in [the correct section](https://docs.google.com/document/d/1Yq5d2M3MgM2vPhUBZ0k5wOmCQst4vND9-2qEZ55-h-Y/edit#heading=h.eo4o8x6pf8z3)
- [ ] Investigate the architectural considerations (note the python-cloudflare library vs using requests and the model implications of all the ds record types)
- [ ] Any info found regarding errors or error handling, be sure to add to the error handling section
- [ ] Answer all open questions regarding performing CRUD operations and follow any guidance marked in the "<>" markers
- [ ] use the test account to try the CRUD operations via command line

### Links to other issues

- [ ]  semi-blocked by #2873 (the other will need to be started first before trying the commands, not fully blocked)

**Comment by vickyszuchin** [comment]
Any "In progress" tickets from Sprint 55 will be moved to the current sprint (Sprint 56) at noon EST (10am MT/9am PST) on Day 1.
