### ISSUE TITLE
Validation Issues on Domain Registrant Form

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#292]
Validation Issues found in QA

- No validation on the state dropdown (when a user doesn't include a state in an address form, there is no validation it hasn't been selected). For example, no error is shown if somoeone doesn't choose a state on https://getgov-staging.app.cloud.gov/register/organization_contact/
- On https://getgov-staging.app.cloud.gov/register/current_sites/, the field does not validate for a website. A user does not have to put in a ".", or can put in a variety of characters. Expected it would validate against a website structure
- No validation or error message if user doesn't confirm reading terms and conditions? https://getgov-staging.app.cloud.gov/register/requirements/
- Validation for email field (example, on https://getgov-staging.app.cloud.gov/register/authorizing_official/) requires a @ symbol and text after the @ symbol, but does not accept an email like cale@cale in that it does not allow user to proceed to next step. However it provides no error messaging

**Comment by loganmeetsworld** [comment]
Related to #262
