### ISSUE TITLE
Spike: Provide Design Artifacts Needed to Set Up get.gov website Infrastructure

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#299]
Provide following artifacts so engineering can set up Netlify and prepare a Federalist site for a user test on the educational content

- [x] @michelle-rago - Update of sitemap/content types for Federalist site ([https://docs.google.com/document/d/1BoCiI5xZ8B5DGkc-od-MBrDRgFli7nAgVBvGvkim4w0/edit#](https://docs.google.com/document/d/1BoCiI5xZ8B5DGkc-od-MBrDRgFli7nAgVBvGvkim4w0/edit))
- [x] @michelle-rago - Develop content for home page
- [ ] @michelle-rago @igorkorenfeld Design of templates types (In Progress) 
- [x] @igorkorenfeld - Product Design of homepage of get.gov (root) including branding (In Progress)
- [ ] @boonerang  Artifact detailing browse path of get.gov -> login

Outcome: Engineering is able to set up a Federalist site with Netlify and hand back to engineering to propagate content

**Comment by michelle-rago** [comment]
Mural for wireframes https://app.mural.co/t/gsa6/m/gsa6/1670961536606/c28c7864aa9273335b9241e76a873f1ed0468f03?sender=michellerago0372

**Comment by loganmeetsworld** [comment]
I have started to implement what we have so far. Preview here: https://federalist-e9f16d18-a4f8-4898-af3d-6e9b4e0c3c48.sites.pages.cloud.gov/site/loganmeetsworld/11ty-gov/
