### ISSUE TITLE
CISA .gov Blog Post

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#30]
- [x] Draft blog
- [x] Review blog post / contribute to it
- [x] Discuss approvals from 18F perspective
- [x] Then finalize

**Comment by colinmurphy01** [comment]
Moving back into backlog to be considered for next sprint.

**Comment by loganmeetsworld** [comment]
Done! Great job @h-m-f-t https://home.dotgov.gov/updates/2022/9/14/making-infrastructure-less-invisible/
