### ISSUE TITLE
Educational content: Election office

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#305]
- [x] Draft content for election offices: https://docs.google.com/document/d/1pgNe7YUd185O6lQFidR7PP7GyMJw0RgOvNTZAy_lmPE/edit
- [x] Review requested from @h-m-f-t and @calerubensteingsa 
- [ ] Share with election SMEs

**Comment by h-m-f-t** [comment]
I asked for feedback from our election security rep – or rather, I schedule-sent an email about it to land when they return from leave next Tuesday the 7th.
