### ISSUE TITLE
Create Script and Scenario Development for Registrar Application Test

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#308]
- [ ] Evaluate the registrar application
- [x] Determine if we need PRA for testing, document (we should not)
- [ ] Create script/scenario document

**Comment by calerubensteingsa** [comment]
12/15:

Initial plan and script shared, more documents forthcoming
Going to join dev standup and talk about ways to join, figure out flows - what type of data to use, sample data, etc
What's it like going through application process

**Comment by boonerang** [comment]
- [Initial plan development and future iterations here.](https://docs.google.com/document/d/12i0OzNlDAxCpo1NG_V6XjWG09_2qPF4Qb9sWh2l31Mo/edit)
- [Script developing here.](https://docs.google.com/document/d/1djXLpo33eyPCwv6JfI67OhA9Mc2lTkv3igYVZ9XEtv8/edit)
- [Prototype screen notes here.](https://docs.google.com/document/d/1_4pj57wps70oeWyP_GIu6ltQ1RtPZiAQLJk2PgKkIQA/edit#heading=h.yzq0ub4gs7e4)

**Comment by calerubensteingsa** [comment]
1/5:

- Discuss at design huddle, identify things to discuss screen-by-screen
