### ISSUE TITLE
R1: Add registrant flow to Mural

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#32]
We should create a fake domain to register (ex. igorville.gov) and add processes discovered to the Mural for user journey flow on the registrant side.

**Comment by igorkorenfeld** [comment]
Authorization letter sent

**Comment by igorkorenfeld** [comment]
Got access to the registrant portal, captured screenshots and stored them on drive

**Comment by colinmurphy01** [comment]
Added to story map.
