### ISSUE TITLE
In the domain application form, alert users who attempt to register a subdomain

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/getgov#324]
The .gov registry only traffics in second-level domains (e.g., cisa.gov). This can be a confusing concept, and we regularly see authorization letters with subdomain requests (e.g., initiative.cisa.gov). 

When someone asks for a subdomain – they type a `.` into the domain field – we should alert them that only second-level domain requests will be evaluated and help them know what to do next.

(In a future state, we can likely connect the requester with the second-level domain's registrant, though that's not MVP work.)

Related to #763 
Related to: #720 
----------------

AC: Develop the content for error messaging.

Additional context:

Currently if a user enters a sub domain this is the output on the screen and they are unable to move forward until the period is removed.

![Image](https://github.com/cisagov/getgov/assets/109625347/8b7504c1-1d77-4d61-97f8-c76eb6e602eb)

**Comment by h-m-f-t** [comment]
Or I guess if someone types _two_ periods, since everyone is likely to type one (something`.`gov).

**Comment by kitsushadow** [comment]
Note: Leverage the Domain naming convention (if there is one) to assist the user in creating their domain name

**Comment by kitsushadow** [comment]
We should learn content or language that goes out today when submissions like initiative.cisa.gov are sent.

**Comment by kitsushadow** [comment]
Evaluate the wording once the www. messaging is removed as well as the prompt users see before filling out their domain request.
