### ISSUE TITLE
Manage Submitted Domain - Implement Withdraw Domain Functionality

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#328]
**Acceptance Criteria**

see below

**Comment by igorkorenfeld** [comment]
Design for the [confirmation page ](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3124%3A32294&node-id=3194-35153&viewport=158%2C512%2C0.17&scaling=min-zoom&starting-point-node-id=3194%3A35488)after "Withdraw request" is pressed. 

[Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3194%3A35153&t=We0rj9wgKCR2m5Gf-1)

Figma [prototype of the flow](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3124%3A32294&node-id=3194-35488&viewport=158%2C512%2C0.17&scaling=min-zoom&starting-point-node-id=3194%3A35488) to help make it clearer:
1. Click "Manage" for the submitted domain
2. Click the "Withdraw request" button
3. Click "Withdraw request" on the confirmation page.

**Comment by igorkorenfeld** [comment]
Updated the date to be "Last updated"

**Comment by loganmeetsworld** [comment]
https://github.com/cisagov/getgov/pull/525
