### ISSUE TITLE
R1: Current state analysis (Content) – Planning and Scheduling

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#33]
- [x] Finish draft a [Research Plan](https://docs.google.com/document/d/1s7bM5WtqTYk64nazpArwgt3ZGr4POmE-Wt3UmYKM9HQ/edit)
- [x] Review with @boonerang 
- [x] Share with team, via slack and address feedback
- [ ] Identify any meetings that need to be scheduled
- [x] Schedule meetings with @h-m-f-t

**Comment by colinmurphy01** [comment]
Research plan was spun up by @boonerang and includes questions that were initially gathered during #6

**Comment by colinmurphy01** [comment]
@michelle-rago tagging you in this for when you're back from OOO as something to consider taking ownership.

**Comment by michelle-rago** [comment]
[Content-related questions](https://docs.google.com/document/d/1s7bM5WtqTYk64nazpArwgt3ZGr4POmE-Wt3UmYKM9HQ/edit#)

**Comment by michelle-rago** [comment]
We gave @h-m-f-t access to the [content-related questions](https://docs.google.com/document/d/1s7bM5WtqTYk64nazpArwgt3ZGr4POmE-Wt3UmYKM9HQ/edit#). He'll answer async and we'll have follow-up convos as needed.

**Comment by colinmurphy01** [comment]
Meeting scheduled with @h-m-f-t tomorrow during coworking, will determine if more time is needed.
