### ISSUE TITLE
Add Options for Organization Type

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#340]
**Acceptance Criteria**

- Under Organization Type, add two options:
- School district: a school district that is not part of a local government
- Other (prompting a field to enter information)

**Comment by neilmb** [comment]
School district is already included since https://github.com/cisagov/getgov/commit/3ad810ee7dbace0edb7ee243d0c1a23e36f29f58

Looking into adding an "Other" and fields to support it.

**Comment by neilmb** [comment]
Google doc conversation at https://docs.google.com/document/d/1ieO5Qm18dMCS04v-HdF6zKSDdzDWSmAyVjUAI21RyRU/edit#heading=h.pg4js1nc27mw indicates that there is no interest in having an "Other" category. Closing this issue.
