### ISSUE TITLE
Education Content: Eligibility for using login.gov

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#356]
- [ ] Draft content for page/intersistial (sp?) for eligibility to create a login.gov account for registrar

**Comment by michelle-rago** [comment]
Is this different from https://docs.google.com/document/d/1bvWPa2i0mrhDR4iNa0cBErMfSJ4RzUHpQ4Zz_YdPzCc/edit?

**Comment by calerubensteingsa** [comment]
Hi @michelle-rago , sorry this comment got away from me

I think we can close this issue, correct? It may have been a dupe or handled elsewhere

**Comment by michelle-rago** [comment]
Yep, good to close
