### ISSUE TITLE
R1: Current state analysis (Screen Inventory) – Planning and Scheduling

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#37]
- [x] Finish draft a [Research Plan](https://docs.google.com/document/d/11mkqiRkXazUAW2Jb1VxslLw6Tr9zDNhzXys4oxas19E/edit?usp=sharing)
- [x] Review with @boonerang 
- [x] Share with team, via slack and address feedback
- [ ] Identify any meetings that need to be scheduled
- [ ] Schedule meetings with @h-m-f-t

**Comment by colinmurphy01** [comment]
Research plan was spun up by @boonerang and includes questions that were initially gathered during #6

**Comment by colinmurphy01** [comment]
@boonerang and @igorkorenfeld we can edit this to reflect the registrant flow that Igor is completing now.

The question is once the screens have been captured, what's next?

@igorkorenfeld one idea as an output of this would be to pair with you on documenting the screens and functionality into a story map for registrants. At that point we can then determine which functions are critical for MVP.

**Comment by igorkorenfeld** [comment]
Uploaded screenshots to drive. Paired with @colinmurphy01 to add notes from the registrant experience to the storymap mural
