### ISSUE TITLE
Updated Landing Page for Registrar Testing

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#371]
**Acceptance Criteria**

- Update https://getgov-stable.app.cloud.gov/'s landing page to be more user-friendly
See current:
![Image](https://user-images.githubusercontent.com/108084972/213550870-dc272d34-289e-419f-9f2f-4536fe1ab33a.png)

**Comment by neilmb** [comment]
Fixing this with a giant "Sign in" button alongside of the changes for #342
