### ISSUE TITLE
Adjust get.gov homepage to updated design

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#380]
We received some feedback about the homepage during demos we should incorporate into the cloud.gov pages deployment.

**Comment by igorkorenfeld** [comment]
Current [homepage design in Figma](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=2404%3A27857&t=6uSK6VBzsnP2kCre-1)
