### ISSUE TITLE
Update requirements based on new guidance

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#383]
- [x] Update content as necessary based on OMB memo
- [x] Document [potential follow-up work](https://docs.google.com/document/d/17-rb8MnDF_IM3movK-emvIQcqEu3NIGJ846qSM8RGHI/edit#heading=h.ni4covqi5nnc)

**Comment by michelle-rago** [comment]
[New OMB guidance will be issued soon](https://federalist-47d0482b-663e-4928-afca-c2337577b510.sites.pages.cloud.gov/preview/cisagov/dotgov-home/memo/registration/requirements/#executive-branch)

**Comment by calerubensteingsa** [comment]
1/31:

- Some discussions with Cameron, update content
