### ISSUE TITLE
Proposal: Remove locks on sidebar to progress in application form

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#393]
# Description

We should remove the locks on the sidebar so that when someone returns to an application they  can go forward to any item. We currently do not save progress in the db, which would be significant development work to achieve. This creates wonky state between multiple applications and when you re-log in you have to progress through the entire application. 

Additional proposal: When opening a previously started application, land on the review page so that a user can see remaining items needed to submit?

# A/C

- As a user, when I begin an application I can jump around and fill out any part of the application - moving to a different part of the application removes all my work if I do not "save"
- As a user, I can review what is completed as part of the application on the "review" page
- As a user, when I return to an application I am directed towards the "review" page
- As a user, when I return to a previously started application I can see any section

**Comment by igorkorenfeld** [comment]
On 2/3 had a discussion where we decided we will not be implementing this as it was important to capture some responses from registrants so that we can conditionally show them relevant examples or ask them additional questions
