### ISSUE TITLE
Update Save Experience to Inform User when a save doesn't have valid data

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#399]
**Acceptance Criteria**

- When a save of a question doesn't have entirely valid data in required fields, add a visual indicator that the save did not save invalid data https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=2798%3A31463&node-id=2800%3A32606&viewport=-133%2C960%2C0.37&scaling=min-zoom&starting-point-node-id=2800%3A33123&show-proto-sidebar=1
- Any valid data is saved to the DB and is available when returning

**Comment by igorkorenfeld** [comment]
We determined that we cannot save partial data and have removed the "Save progress" button. Instead we now rely on error messaging.
