### ISSUE TITLE
Sketch initial database schema

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#4]
Keep this simple.

- [x] Identify data models
- [x] Chose a database https://cloud.gov/docs/services/relational-database/ 
    - [x] Draft the ADR for database choice
        This ADR may reflect a lack of choice, i.e. choice was random in interests of time.
- [x] Present to team initial thoughts on data modeling

**Comment by SSPJ** [comment]
This has been accomplished. [Relevant Slack thread here](https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1661970335955509) 🔒 

Next steps are to formalize in an ADR which models/fields we can include right now (and create a pull request to include them), then to continue the work of drafting additional models on a separate git branch, to be pulled into ongoing work as they become formalized through discussion and user research.

**Comment by SSPJ** [comment]
I created #92 as a follow up task.
