### ISSUE TITLE
Investigate CRM providers

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#40]
- [ ] Investigate and document what are basic feature and compliance needs
- [ ] Understand what providers exist in the FedRamp marketplace
- [ ] Speak with Login Partnerships team about their investigation into this space
- [ ] Speak with MD&P about their investigation in this space
- [ ] Document early analysis of pros and cons of various options and discuss as a team

Decide if we should conduct formal market research and/or pursue sandboxing or prototyping.

**Comment by loganmeetsworld** [comment]
Rolling this into existing enterprise software investigation
