### ISSUE TITLE
Set up skeleton page for accepted domain request

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#423]
**Acceptance Criteria**

- When a domain is accepted, domain should appear in the Registered Domains section of the dasboard
- Clicking on "Manage" should bring user to a "Domain Overview" page
- Should match the comps as close as possible: See updated mockup in comments

**Comment by igorkorenfeld** [comment]
Updated Figma with mockup:
https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3239%3A36567&node-id=3239-37241&viewport=-95%2C341%2C0.22&scaling=min-zoom
