### ISSUE TITLE
Integrate epplib for invoking calls to the registry

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#432]
Test against OT&E that all commands work; troubleshoot any that do not.

- [x] Login
- [x] Logout
- [x] Domain
    - [x] Check
    - [x] Info
    - [x] Create
    - [x] Update
    - [x] Delete
    - [x] Renew
- [x] Host
    - [x] Check
    - [x] Info
    - [x] Create
    - [x] Update
    - [x] Delete
- [x] Contact
    - [x] Delete
    - [x] Update
    - [x] Info
    - [x] Check
    - [x] Create
- [x] Create a changelog of modifications to epplib
- [x] Contribute a list of patches back to FRED project

**Comment by SSPJ** [comment]
I've moved DNSSEC to #634. Everything else [is merged](https://github.com/cisagov/epplib/pull/1).
