### ISSUE TITLE
Registry BASIC error handling - UX/UI

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#433]
Background:
When messages are sent via EPP to the registry an error may come FROM the registry that indicates 1.) user entered bad data or 2. We are unable to connect to the registry.  

Currently, on a registry connection error our system says "Cannot connect to the registry" and when a user enters bad/incorrect data we say "Registry error occurred: " followed by the exact error content from the registry which is very technical and may even reference xml.

##Acceptance Criteria

- [x] content is created  for a "User entered bad data" error message
- [x]  content is created  for a "Registry Connection" error message

Related Tickets:
Related to: #1103 
Related to: #1104 
 

###Additional Context

Suggestions for a User entered bad data error message:

-  "Something went wrong. Please double-check all the data you've entered and try your transaction again. If you're sure the data is correct and the problem persists, please try again later as the system issue will be resolved."

- "Your input is incorrect, please review the documentation"

Suggestions for Registry Connection:
-Something went wrong, try again later"

**Comment by kitsushadow** [comment]
possible discussion of a queueing system. EG: RabbitMQ or something

**Comment by PaulKuykendall** [comment]
this ticket has been repurposed to general error messaging for MVP. Better error handling will follow MVP.

**Comment by gabydisarli** [comment]
Working on the copy here https://docs.google.com/document/d/12qxl6evZw16dT-TB9iu3YLjKdwwL5KqIYQJV4uncAXg/edit?usp=sharing

**Comment by gabydisarli** [comment]
> Working on the copy here https://docs.google.com/document/d/12qxl6evZw16dT-TB9iu3YLjKdwwL5KqIYQJV4uncAXg/edit?usp=sharing

Copy is ready to go and be implemented
