### ISSUE TITLE
Develop Research Plan for Testing get.gov Site

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#445]
- Develop testing plan for get.gov unauthenticated website

**Comment by boonerang** [comment]
Draft in progress.

**Comment by boonerang** [comment]
[Plan drafted and updated,](https://docs.google.com/document/d/1JQ1tTh-RdBrM9wKdKWxIDhUzaOL50GcrqLJ15_K1_bs/edit?usp=sharing) next step is figuring out recruiting and cascading dates.
