### ISSUE TITLE
Remove "save progress" button at bottom of form

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#450]
Follow up to #448, we want to remove the "Save progress" button on the form so that we only have one button to progress. 

Reviewer: @igorkorenfeld

**Comment by kewlguy781** [comment]
I ran into some concerns with the test suite. How its written is that once it hit the "save progress" it does the data validation. I do not want to scrap them and felt that data validation should be in. I am going to talk with @SSPJ about it and see if there are any way we can do data validation without save progress feature. 

cc: @loganmeetsworld
