### ISSUE TITLE
Research federal use cases and needs

### ISSUE THREAD

**Issue by boonerang** [cisagov/getgov#475]
Research the needs of federal users for the registry. Are there specifics to their use cases and flows we should plan for?

Goal(s) are to understand what, if any, differences might exist for federal users compared to the SLTT flow. The research is looking past MVP and to future design and development. Further conversations will provide clarify of timeframe.

**Comment by boonerang** [comment]
Early conversations point to finding past federal customers to understand the scenarios that come up most often.

[Earliest notes here](https://docs.google.com/document/d/1fq4djmSJ7Vs8ckXveSNUdxdEbxcREaJ9iUSZzUneeDQ/edit#), will be update as we go.

**Comment by boonerang** [comment]
[More details notes put together after meeting with OMB.](https://docs.google.com/document/d/1-FczuKDySWYlJtBg54rOInBk5lPYzu3ebQHru8juURg/edit?usp=sharing)

Federal use cases look like they will have some distinct differences and details, moving approvals and adjudication to OMB and their designates.

**Comment by boonerang** [comment]
[Federal use case w/ OMB updated here](https://docs.google.com/document/d/1yl5rtU-n8LhtHT4qUDu61sfJ0JBqMmjLhb9VLl4kcRs/edit?usp=share_link). Could be a template for a similar "admin/approver" with another branch if necessary.

**Comment by michelle-rago** [comment]
@gabydisarli @PaulKuykendall FYI
