### ISSUE TITLE
Set Up Functionality to Authenticate and Assign User to an Accepted Domain

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#477]
**Acceptance Criteria**

- Add functionality to User Management so that if a user is added to an accepted domain a email is generated prompting them to set up a login.gov account and then be assigned to the domain

Doc: https://docs.google.com/document/d/1vmVKmxQ7G4uJ7S6c27RNpTDKbAjCxt3PQ-qgCb5Uhq4/edit?usp=sharing

See thread: https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1679344501659889

**Comment by neilmb** [comment]
Django models and views are now done in the domain's user management along with their unit tests on https://github.com/cisagov/getgov/tree/nmb/user-invitations

Still need to make emails be sent when we create invitations, and "retrieve" existing invitations when a user logs in.
