### ISSUE TITLE
You have been added to a domain- email notification for .gov accounts

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#482]
See PB: https://www.google.com/calendar/event?eid=MmUzc3FkNjZxOWl1aWxiODExZTAxNGRydDZfMjAyMzAzMjJUMTgwMDAwWiBsb2dhbi5tY2RvbmFsZEBnc2EuZ292

**Acceptance Criteria**
- Will be sent for users who have get.gov accounts in addition to ones who do not
- Will be sent for users who are added to one or multiple domains (from the domain management page)
-update unit tests
- The subject line and copy is the same for all users (replace old copy)

CC @neilmb 

- [x] [Draft email](https://docs.google.com/document/d/1HnMdniAB9INphrLwKjiACyNLrenyXy0QFf0-yz4EStI/edit?usp=sharing) @michelle-rago 

-------------

Relates to: #507 

implementation note: 
in form_valid on views/domain.py, it may be as simple as always sending an email_invitation.

**Comment by kitsushadow** [comment]
ToDo: Split this ticket up

**Comment by abroddrick** [comment]
This is similar to what was done but still needs implementation

**Comment by kitsushadow** [comment]
If you dont have a get.gov account you wont get an email.

**Comment by abroddrick** [comment]
@CocoByte are you working on this one?

**Comment by therealslimhsiehdy** [comment]
Clarification Q: Are we replacing the "domain invitation" email subject + text with this new "you’ve been added to a domain" email subject/text?

**Comment by abroddrick** [comment]
tagging @Katherine-Osos or @gabydisarli for the above question
