### ISSUE TITLE
Remove landing sign in page on Django app

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#486]
We will remove the landing page with the sign in button on the django app

A/C: All users get a page where they can either log in or start their login account creation

**Comment by neilmb** [comment]
Breadcrumbing: We need to add the `@login_required` decorator in `registrar/views/index.py` and modify the template in `registrar/templates/home.html` to take out the un-logged-in page content.

**Comment by loganmeetsworld** [comment]
Suggestion on #488 to make a middleware instead of added decorators to each view.
