### ISSUE TITLE
Implement methods to satisfy the test cases for registry integration

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#493]
Builds on #492 . Write the code.

Relies on #636 having been completed.

- [ ] Placing and removing client hold (suspending)
- [ ] Placing and removing client X prohibited (locking)
- [ ] Deleting a domain
- [ ] CRUD actions on contacts
  - [ ] Create contacts using default values and link them to a domain
  - [ ] Add an email address to a security contact and set the email to be publicly disclosed
  - [ ] Remove an email address from a security contact by setting it to the CISA default and setting it to not be disclosed
- [ ] CRUD actions on nameservers
  - [ ] Add nameservers by creating host objects and linking them to a domain
  - [ ] Remove nameservers by unlinking host objects from domains and deleting them
  - [ ] Update IP addresses on host objects
- [ ] CRUD actions on DNSSEC
  - [ ] View existing DS Data or Key Data
  - [ ] Add new DS Data or Key Data (but not both)
  - [ ] Remove existing DS Data or Key Data
  - [ ] Replace existing DS Data or Key Data by indicating which item to remove and which item to add

Due to size, these items may need to be broken into smaller tickets and worked over multiple sprints.

**Comment by vickyszuchin** [comment]
Tickets created for the scope of the work.

**Comment by PaulKuykendall** [comment]
This item was broken into parts, to resolve this ticket. See comments above.
