### ISSUE TITLE
Timeboxed Investigation to Migrate Existing Registrar Data

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#499]
Acceptance Criteria

- Timebox (1 sprint?) investigating migration of data
- Write up findings/share approach
- Identify open questions and next steps

**Comment by neilmb** [comment]
We have a cut data from Verisign's registry/registrar system. We want to investigate taking that data and integrating it into our new registrar system. Let's look at their data to understand it, then see about making a migration script that imports that data into our registrar's data model.
