### ISSUE TITLE
Limit Users Per Domain to 10 Accounts

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#506]
**Acceptance Criteria**

- Limit accounts per domain to 10 accounts

**Comment by igorkorenfeld** [comment]
Should make a note about the maximum on the user management page so that domain managers know

**Comment by abroddrick** [comment]
are we still doing this? We talked about doing just 1 domain max

**Comment by h-m-f-t** [comment]
@abroddrick I think this issue is about post-approval user management, where the contact that created a domain could add ≤9 other accounts, not the issue to limit users without an approved domain request to only 1 request.

**Comment by h-m-f-t** [comment]
Closed because we're not limiting the number of users who can manage a domain for now.
