### ISSUE TITLE
Content Decision: Email content for users being added to account via the domain management page

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#507]
This email will be sent when a user is added to a domain via the domain management page and they already have a get.gov account. 

**Acceptance Criteria**
- [Email content ](https://docs.google.com/document/d/1HnMdniAB9INphrLwKjiACyNLrenyXy0QFf0-yz4EStI/edit?usp=sharing)can be the same as #482 (to be approved by @michelle-rago )
- Design to verify if the current content is correct or provide desired changes

-------------

Relates to: #482 

-------------

What the current system sends

![Image](https://github.com/cisagov/getgov/assets/107440934/37265711-8713-4904-a6ae-0902d7c49dd7)

-------------

- [x] Confirm email does send
- [x] Confirm the content is what we want it to be. #482

**Comment by abroddrick** [comment]
email sending portion for current get.gov users will be implemented in #482 but the email currently sends if the email added is not a get.gov email.

**Comment by gabydisarli** [comment]
@h-m-f-t tagged you in the above Google doc Michelle created

**Comment by gabydisarli** [comment]
Email content is confirmed and approved ✅
