### ISSUE TITLE
Remaining Design for Approved Domain Section

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#527]
**Acceptance Criteria**

- A design is available for engineering to build the remaining pages for the accepted domain section

- [x] Domain Overview -> [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3239%3A36567&node-id=3239-37241&viewport=-8%2C3053%2C0.68&scaling=min-zoom) || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3239%3A37241&t=MexjlQKFZMDrjCmK-1)
- [x] DNS Pages -> [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3816%3A38507&node-id=3816-38717&viewport=159%2C326%2C0.23&scaling=min-zoom)  || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3816%3A38717&t=MexjlQKFZMDrjCmK-1)
- [x] Organization and Mailing Address -> [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3826%3A43000&node-id=3826-43485&viewport=-1704%2C-798%2C0.33&scaling=min-zoom&starting-point-node-id=3826%3A43485) || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3826%3A43485&t=MexjlQKFZMDrjCmK-1)
- [x] Authorizing Official ->  [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3826%3A44344&node-id=3826-44345&viewport=519%2C435%2C0.45&scaling=min-zoom) || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3826%3A44345&t=MexjlQKFZMDrjCmK-1)
- [x] Your Contact Information -> [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3850%3A37010&node-id=3850-37011&viewport=375%2C522%2C0.21&scaling=min-zoom) || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3850%3A37011&t=MexjlQKFZMDrjCmK-1)
- [x] Security Email -> [Prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=3764%3A36551&node-id=3764-36723&viewport=361%2C555%2C0.29&scaling=min-zoom) || [Artboard](https://www.figma.com/file/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?node-id=3764%3A36723&t=MexjlQKFZMDrjCmK-1)
- [x] User Management -> Updated on the application, won't be updating Figma

**Comment by igorkorenfeld** [comment]
@michelle-rago would mind reviewing the paragraph of text and confirmation message for Org mail, AO, and Your contact pages? I took the parts that seemed relevant from the form, but wonder if there is anything missing or anything we would want to phrase differently once approved.

**Comment by igorkorenfeld** [comment]
Thank you for the great feedback @michelle-rago, believe everything but the footer should be updated now.
