### ISSUE TITLE
Copy data of users/contacts from Application after domain are approved

### ISSUE THREAD

**Issue by kewlguy781** [cisagov/getgov#541]
Currently the only information we stored about users/contacts are in the application. We do not have anything in place to copy and store these information once domain is approved which caused the follow ticket to be stuck:
#527 #517 #519 #520 and #516

Revisit the transition of Pending application into approved should copy these datas into respective places, which will then can be used for these tickets above.

**Comment by kewlguy781** [comment]
@loganmeetsworld

**Comment by loganmeetsworld** [comment]
Implementation to be discussed at meeting this afternoon and will impact how we handle managing this information as part of existing registrant experience moving forward.

**Comment by kewlguy781** [comment]
https://docs.google.com/presentation/d/1VlUy-hGhI8bF_JompbzKzfrLzKiwfm8dOpSKiDKw1rQ/edit#slide=id.p

**Comment by kewlguy781** [comment]
After meeting with @h-m-f-t @SSPJ and @igorkorenfeld-

for the database, we will need to make a copy of the information and allow for users to change while retaining the original state of application.

for the contact part, we will need to copy of that as well (because they are stored as `registrar.Contact`, they need to be left alone. May want to rename that into `registrar.ContactRegistration` vs `registrar.ContactInformation` (or something like that)

for WHOIS, the MVP will only use security contact information (design is already there for that). We will need to re-add security back, but only into `DomainInformation`

**Comment by kewlguy781** [comment]
🙌  its done!
