### ISSUE TITLE
Prevent unauthenticated access by using middleware

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#543]
It is easy to forget `@login_required` decorators and `LoginRequired` mixins, so a middlware layer should be installed to ensure only ok-listed routes are accessible when a user is not signed in.

A suitable 3rd party middleware package may not exist, so it may be necessary to write a small middleware. Existing examples in the codebase can be used.

Middleware may also help with bugs like #537 and #405. It could also resolve and close #486.

This work may intersect with #544.

**Comment by loganmeetsworld** [comment]
As part of this we should also remove the landing page view and only have home be the dashboard (thus requiring authentication for every view in the site)
