### ISSUE TITLE
Sprint Goal: Conduct user testing on unauthenticated site and registrar

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#548]
- [x] Script prep for sessions
- [x] Writeup details for observers
- [x] Share schedule with observers
- [x] Session on 5/1
- [x] Session 1 5/2
- [x] Session 2 5/2
- [x] Session 5/3
- [x] Session 5/4
- [x] Session 5/10
- [x] Session 5/11
- [  ] Session 5/12

**Comment by boonerang** [comment]
Sessions scheduled week of 5/1, invites in dotgov team calendar. One more session still possible for the week of 5/1.

**Comment by boonerang** [comment]
Sessions winding down, should be finished 5/12, may have one or two others appear but this might be the last burst.

**Comment by boonerang** [comment]
We are going to call it with the 7 sessions we did. Part of this is to close the work out strong and part is to have the participant in the pipeline for the next round of research or conversation. (A screened lead you keep for the next round is a gift you give yourself.)
