### ISSUE TITLE
Resolve questions in domain status transitions doc / Confirm status labels

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#554]
Resolve questions, confirm status labels, update the app as needed, and document new features represented in the doc https://docs.google.com/document/d/1I4sx-z2pbxdehj2Skci_sFZQvV8gEKE-nLu1CxxvaGc/edit#heading=h.offzhsrbdkub

The analyst research could inform the level of status transparency we can provide to users about their requests (e.g., Your request has been assigned; Your authorizing official has been approved).

**Comment by kitsushadow** [comment]
Notes: Status Transition workflow diagram

**Comment by h-m-f-t** [comment]
Questions in the doc have been resolved.
* "Submitted" stays
* "Investigating" will be replaced with "In review"
* "Sent back" (which doesn't currently exist) will be "Action needed" (#757)
