### ISSUE TITLE
Design the "check availability" experience on {beta.}get.gov

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#561]
Design the UX on the public site for a potential registrant to search and discover whether the domain they want is available. This feature is linked from several get.gov pages (e.g., [Before you request a .gov domain](https://beta.get.gov/domains/before/)).

Relates to #781.

A/C: Figma diagram to support implementation

**Comment by gabydisarli** [comment]
New [Figma design for check availability feature](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=1813%3A27518&mode=design&t=3grPKvKJpmrKHlIq-1) is ready for implementation! 🎉
