### ISSUE TITLE
Deprecation of cflinuxfs3

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#591]
Following along the deprecation of [clinuxfs3](https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/) in cloud.gov, we need to update this for all our environments. 

- [x] stable
- [x] rjm
- [x] jon
- [x] ik
- [x] nmb
- [x] spj
- [x] ab
- [x] bl
- [x] mr

**Comment by neilmb** [comment]
https://github.com/18F/tock/pull/1606/files is an example of how to do this, it looks like `s/cflinuxfs3/cflinuxfs4` in `ops/manifests/manifest-*.yaml` will do the trick.

**Comment by neilmb** [comment]
First try at https://github.com/cisagov/getgov/tree/nmb/591-cflinuxfs4 but not totally sure what we need to do to restage or redeploy everything.
