### ISSUE TITLE
Sprint Goal: Scope design work for analyst experience

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#592]
A/C: Scoped work delivered for the analyst experience for design - a set of user stories for our _future_ state that is complete enough for beginning to wireframe. 
A/C: Holistic understanding on the part of design on the analyst workflow

Milestones: 
- [ ] #597 
    - [x] Session: Walkthrough the admin django and the possibilities with design and engineering 
- [ ] #598
- [x] #599 * 
    - [x] Stretch goal: interviews conducted and completed with analysts walking through their workflow
- [x] #600 **

*Preparation for this should be walking through the full domains.dotgov.gov process, what do they need from a registrar? What do they need from a registrar admin interface? What do they need from a helpdesk integration? 
**Part of the analyst purview is reviewing domain submissions. The process changes we've made propose substantive changes to their workflow outside of the UI (as part of the domain application we've created). Would this be sufficient for reviewing an application for eligibility?

**Comment by Katherine-Osos** [comment]
We did not completely meet this sprint goal. As next steps, we think the following stories are needed: 
- Officially define and document the MVP requirements
    - Create a user journey with MVP features
- Prioritize the challenges and needs
    - Heat map voting of the top challenges and needs
    - Impact/Effort prioritization workshops

The outcome of these stories will provide a user flow for MVP that our team can reference during design and implementation, as well as a roadmap for what features will best support the analysts’ workflow.
