### ISSUE TITLE
Workshop: Research planning and prioritization for R1-3

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#6]
Purpose: Host a research planning and prioritization discussion for R1-3 in order to begin executing critical primary research activities that will enable us to pursue our primary and secondary goals.  

- [x] Host discussion with @michelle-rago prior to OOO
- [x] Host discussion with team in coworking, on Tuesday
- [x] Decide on R1-R3 research focus areas, on Tuesday
- [ ] Document in github repo or Google Drive, depending on what works best

**Comment by colinmurphy01** [comment]
Using this doc to organize thoughts: https://docs.google.com/document/d/1g9RGZ3dV5Qhte8BXR9qIxYZPoBcwHkXeuI0DR7cuMUc/edit

**Comment by colinmurphy01** [comment]
Assigned to Boon

**Comment by colinmurphy01** [comment]
@boonerang I believe this is done? Let's confirm how you want to document things? Most of it probably lives in google drive, but I'd love to put a summary of our research strategy in the github repo.

**Comment by colinmurphy01** [comment]
@boonerang is organizing our research folders to the team only.

**Comment by boonerang** [comment]
Done, moved into Google folders
