### ISSUE TITLE
Test information generated by current get.gov domain application process with analysts

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#600]
A/C: Async interviews conducted where we give analysts a domain request with all content generated as part of a "real" user going through the form and ask them if they would be able to determine eligibility with just this information. 

Part of the analyst purview is reviewing domain submissions. The process changes we've made propose substantive changes to their workflow outside of the UI (as part of the domain application we've created). Would this be sufficient for reviewing an application for eligibility?

**Comment by h-m-f-t** [comment]
- [ ] Prepare test submissions using recently reviewed domain submissions (@h-m-f-t, see [Slack convo](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1684270172856679?thread_ts=1684258122.822919&cid=C03QM0JGSQG))
- [ ] Present that info to analysts in an interview (perhaps #599, perhaps a separate conversation). Could be a PDF or screenshot.

**Comment by gabydisarli** [comment]
Workshop planned for today 5/25 with analysts to walkthrough test submissions
