### ISSUE TITLE
Finalize banner and related content for launch of beta.get.gov

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#601]
A/C: Acceptable content for making potential registrants aware that beta.get.gov is a test site related to test content.

- Run this content and framing of the site through CISA review and @h-m-f-t approval. 
- Tour the site with an eye towards viewing the site as a beta

**Comment by michelle-rago** [comment]
We do want to make the banners on beta.get.gov and the authenticated site the same. Should that be a separate ticket @loganmeetsworld?

**Comment by loganmeetsworld** [comment]
[Cloud.gov](http://cloud.gov/) pages: https://federalist-877ab29f-16f6-4f12-961c-96cf064cf070.sites.pages.cloud.gov/preview/cisagov/getgov-home/beta-banner/ (PR: https://github.com/cisagov/getgov-home/pull/77)
Django: https://getgov-ik.app.cloud.gov/ (PR: https://github.com/cisagov/getgov/pull/638)

**Comment by michelle-rago** [comment]
Drafted [potential blog post](https://docs.google.com/document/d/1CgBCwbVNjbZkNXaCNR36UMUSsqcOsiK_7P7G6PJ2MrY/edit#heading=h.o4q763kt2i0h) if we want to go in that direction @h-m-f-t
