### ISSUE TITLE
Sprint Goal: EPP hand-off

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#603]
For this sprint the highest priority is knowledge transfer and ensuring the new team is empowered to continue the work of registry integration.

To be completed:

- [x] #633 
- [ ] #492 

Up next, sprint 22:

- #645
- #636 

Other tickets currently in this epic, roughly ordered by dependency: 

- #634 
- #493 
- #562 
- #433 
- #579 
- #494 
- #632

**Comment by kitsushadow** [comment]
Will add a ticket for OT&E connectivity in the event sandboxes are not connected.
