### ISSUE TITLE
R1 - Develop Outreach Materials

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#64]
- [x] Draft outreach communications, include additional accessibility needs
- [x] Review and edit communications with another team member

Consideration: Cameron sending initial email, 18F owning operational side

**Comment by igorkorenfeld** [comment]
Created email templates, shared with 18F team and Cameron.

**Comment by colinmurphy01** [comment]
@igorkorenfeld is the review complete? Do you need anyone else to review?
