### ISSUE TITLE
Implement test cases for registry integration

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#645]
Implement the test cases drafted in #492 .

This will require mocking some external dependencies (notably the registry, but perhaps others).

**Tests are not required to pass.** This ticket is complete when all the draft test cases run.

Green (passing) tests are part of #493 .

**Comment by kitsushadow** [comment]
merge into the implementation ticket

**Comment by kitsushadow** [comment]
Closing as a Duplicate
