### ISSUE TITLE
[Story]: Research and Collate past work

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#677]
### User Story

Review past work from @neilmb, capture, and collate into a fresh branch. Anything that should be documented can be provided to @kitsushadow for relocation.

### Acceptance Criteria

Past data and understanding as well as locations for content is captured to enable next work.
EG. Scripts, GitOps, locations of csv's etc.
Add in the comments are next steps for progressing forward.

Review
https://github.com/cisagov/getgov/blob/main/src/registrar/management/commands/load_domains_data.py

https://github.com/cisagov/getgov/blob/main/src/registrar/management/commands/load_domain_invitations.py. 

Could someone review that code and the notes in https://github.com/cisagov/getgov/blob/main/docs/operations/data_migration.md

**Comment by abroddrick** [comment]
@kitsushadow This has been completed, can I just close the ticket?

**Comment by kitsushadow** [comment]
Lets discuss next actions and create tickets then we can close.
