### ISSUE TITLE
Workshop implementations for demo and review of Analyst Workflows in Django Admin

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#680]
As a team, utilize research captured from Rachid and Design to workshop implementations for confirmation and demo.

AC:
1) Design can be reviewed by Analysts for feedback regarding usability.
2) Design can be reviewed by Engineering for feedback regarding feasibility.

**Comment by kitsushadow** [comment]
@kitsushadow review ACs

**Comment by kitsushadow** [comment]
blocked by #753
