### ISSUE TITLE
[Bug]: Show requested domain and any alternate requests when managing submitted application request

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#685]
### Current Behavior

The Manage page* in the registrar does not currently display an applicant's requested domain or alternate domains. 

*Manage Page = The page users can access after submitting a request by clicking "Manage" on their dashboard.

### Expected Behavior

When viewing the Manage page, applicants should see their requested domain and alternate domains.

### Steps to Reproduce

1) Submit a domain request in the registrar
2) On the registrar dashboard, click on the "Manage" link next to that domain request
3) View the info on that page

### Additional Context (optional)

Take a look at the review and submit page on the domain request

**Comment by abroddrick** [comment]
Shouldn't the user just see the name of their name not the other domains? @Katherine-Osos

**Comment by Katherine-Osos** [comment]
@abroddrick This is the "manage" page for an application (not an approved domain), so the alternate names the user submitted may end up being what gets approved. Therefore, I think the user needs to see everything they put in their application.

**Comment by Katherine-Osos** [comment]
@abroddrick This is the "manage" page for an application (not an approved domain), so the alternate names the user submitted may end up being what gets approved. Therefore, I think the user needs to see everything they put in their application.
