### ISSUE TITLE
[Bug]: Nameserver display isn't correct for new domain interface

### ISSUE THREAD

**Issue by neilmb** [cisagov/getgov#687]
### Current Behavior

The new domain interface that we are building has changed the return type of the `nameservers()` method. The domain overview page displays the name servers in a strange way because of the change in that method.

![Screenshot 2023-06-07 at 9 46 25 AM](https://github.com/cisagov/getgov/assets/443389/de3c4857-6355-4594-b79f-84f4944d4701)

### Expected Behavior

The list of nameservers should not include any parentheses or commas.

### Steps to Reproduce

1. Visit the approved domain overview page at /domain/<id>

**Comment by therealslimhsiehdy** [comment]
Hi @neilmb, we (@erinysong and I) just wanted to confirm what end result we want displayed for this ticket:

Current: `('http://ns1.helloerin.com', [89.89.89.89])`

To confirm, do we want it to display like this with an IP addresses:
`'http://ns1.helloerin.com', [89.89.89.89]`

And like this without an IP address:
`'http://ns1.helloerin.com'`

Or if we are completely off, would you mind providing us with examples? Thank you!

**Comment by neilmb** [comment]
A couple thoughts: you can't include the `http://` because these aren't websites that are accessed over HTTP, so just use the hostname `ns1.helloerin.com`. I think if there is no IP address with it (the list is empty) then we shouldn't have any indication of the second part of that return type, so just `ns1.helloerin.com` in that case. If there is are IP addresses with them, how about this `ns1.helloerin.gov (89.89.89.89)` or `ns1.helloerin.gov (89.89.89.89, 89.89.89.90)` if there's more than one. (FYI they only have IP addresses with them if the nameservers are in the .gov zone.)

And maybe more importantly, these are really design questions, so I suggest you pick something and go with it and then ask on #dotgov-disco channel to make sure that they see what you chose in your PR when they review it, and be ready to change it to their much better ideas than mine.

**Comment by therealslimhsiehdy** [comment]
Adding Slack conversation about Nameserver and IP address conversion here: https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1698105246473389

Because we are currently getting an epp.Ip object, we are just going ahead with converting `[]` to `()`, see below for example:

`[IP(addr='127.00.0.1', ip='v4'), Ip(addr='::1', ip='v6')]`  -> `(IP(addr='127.00.0.1', ip='v4'), Ip(addr='::1', ip='v6'))`
