### ISSUE TITLE
Proposed UI for approved domain requests

### ISSUE THREAD

**Issue by igorkorenfeld** [cisagov/getgov#697]
### Ticket Description

We had a [discussion in slack](https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1686150566878219) about what should be displayed to users once a domain request has been approved. I am proposing this [updated UI](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=4702%3A38556&type=design&node-id=4702-38557&viewport=607%2C209%2C0.2&scaling=min-zoom&starting-point-node-id=4702%3A38557&show-proto-sidebar=1) for displaying approved requests and viewing past (archived) requests.

A few notes with questions for feedback:
- I am suggesting that under "Registered domains" we leave off the status column. If it only displays "approved" then I am not sure how much value it would provide. However, I may be missing other important statuses that may need to be displayed here? It also helps differentiate a bit from the approved domain request that will now appear in the "Archive" section with an "Approved" status. 

- Similarly under "Archive" I am suggesting we rename this section slightly from "Archived domains" to just "Archive." The idea is that it could contain domains that have expired in addition to old requests. Do we need to accommodate expired domains (i.e. will those continue to exist and do we want to show them to registrants)? Should it instead be "Archived requests"? 

- Is there additional language we want to include on the detailed view of the approved request? I put in some text to start, but any feedback or additional thoughts are welcome here. 

### Issue Type

design review

**Comment by gabydisarli** [comment]
> I am suggesting that under "Registered domains" we leave off the status column. If it only displays "approved" then I am not sure how much value it would provide. However, I may be missing other important statuses that may need to be displayed here? It also helps differentiate a bit from the approved domain request that will now appear in the "Archive" section with an "Approved" status.


I agree with this. It helps differentiate domain from domain request which strengthens the purpose behind the Archive section.

> Similarly under "Archive" I am suggesting we rename this section slightly from "Archived domains" to just "Archive." The idea is that it could contain domains that have expired in addition to old requests. Do we need to accommodate expired domains (i.e. will those continue to exist and do we want to show them to registrants)? Should it instead be "Archived requests"?


I'm starting to wonder whether we need to rethink the tables of this dashboard to have more generalized headers with statuses to differentiate them? [Like this](https://www.figma.com/proto/9sZmdp5XS0SEzDutiw9jhu/Gaby's-Sketch-Pad?page-id=0%3A1&type=design&node-id=2-3730&viewport=-48%2C273%2C0.37&scaling=min-zoom). I may be way off base here, but the idea occurred to me to share, I wonder what you think?

> Is there additional language we want to include on the detailed view of the approved request? I put in some text to start, but any feedback or additional thoughts are welcome here.


This domain request has been approved and is now a registered .gov domain.  Below you can find an archived summary of your request.

Suggestion: _This domain request was approved on [date]. Below you can view an archived copy of your request for your records._

**Comment by gabydisarli** [comment]
I realize I'm kind of contradicting myself with the my first and second points. Hopefully that's not too confusing for you, let me know I can add more words to clarify.

**Comment by igorkorenfeld** [comment]
Thanks both! The way I am thinking about the "Archive" section is an area that stores "items" that users don't regularly reference or have to care about, but may want to reference. What may help clarify some of the decisions around this UI – do _registered_ domains still expire and is it something we would expect a user to take action on quickly? Or will expired _registered_ domains be just another reference users may want to look at some point? 

If they are something that we want to encourage user action on, then I think it make sense to keep them at the top as Gaby suggests. But if not then I'd advocate moving to the bottom under a grouped "Archive"

@gabydisarli I like you suggestion for the updated text. As I understand it we currently don't store the approval date, only the creation date and last updated dates. This is something that it sounds like the team could change, but would require some additional engineering work.

**Comment by gabydisarli** [comment]
> do registered domains still expire and is it something we would expect a user to take action on quickly?
That's a good question. What's the proposed flow for when registrants want to re-activate an expired domain? Is that something we'll even offer them? 

> Or will expired registered domains be just another reference users may want to look at some point?
My thought was it would be a reference for users to look at but also they could take the action of renewing here. But, I may be spinning my wheels in the wrong direction here if that's not something we're planning to offer at the start.

> But if not then I'd advocate moving to the bottom under a grouped "Archive"
My follow up suggestion would be to rename the section Archived Domain requests if that's all to be contained in that section. My thought being it would be difficult to determine whether the item in the table was a domain request or a domain if both item types got placed in the Archive section. 

To your last point, I don't think it's something we need to bring in neccessarily, so how about 

_This domain request was approved ~on [date]~ and is now a registered .gov domain. Below you can view an archived copy of your request for your records._

**Comment by h-m-f-t** [comment]
Domains are registered for a year but don't automatically expire ([get.gov](https://get.gov/registration/requirements/#determining-eligibility:~:text=.gov%20domains%20are%20registered%20for%20a%201%2Dyear%20period%2C%20but%20do%20not%20automatically%20expire.)). In practice, domains that go past their due date either get renewed or get deleted from the zone; there's not really a _domain state_ of "expired" (as opposed to a request, which can expire). 

Being able to see that a formerly registered domain was deleted is interesting and likely useful, but I don't think it's something we'd need to encourage a user to act on.

We can do research about this, though I think a request that was activated should _only_ show up in "Registered domains" and nowhere else on this page.

**Comment by gabydisarli** [comment]
Thinking through this a little bit more.

I like the idea of having the historical record of an activated domain request live inside of the domain's management page. My concern would be changing up the mental model for folks who get used to seeing the request living inside of the domain dashboard while its in the review phase and then suddenly disappearing as it gets turned into an active domain. @igorkorenfeld @h-m-f-t thoughts?

**Comment by h-m-f-t** [comment]
> folks who get used to seeing the request living inside of the domain dashboard while its in the review phase and then suddenly disappearing as it gets turned into an active domain.

My sense is that users won't be too confused by this, since getting a request into "Registered domains" is the primary reason they are coming us. 

I also like the idea of giving a link to a domain's original request inside the domain management page. Either way, though, it's unclear to me why a registrant would need to review the request post-approval.

**Comment by igorkorenfeld** [comment]
I like this idea as well. And I agree, my guess is that the movement of the request to a registered domain seems like it would be clear (particularly if there are only a few items in those tables). I think it's a good approach to start with and will be something to listen and test for in the future. In answer to your question @h-m-f-t I think the main purpose would be for reference – perhaps to fill out a new domain request, or for their own record keeping. 

To expand on the change If we go with this approach, we would add another section inside of the domain's management page, and the only items that would go in to this archive sections are either domain requests that were rejected or domains that have been deleted. Does that sound right to you two?

**Comment by gabydisarli** [comment]
I'm fine with that approach. We can see how the flow works for folks when we do testing on the domain management experience. 

 the only items that would go in to this archive sections are either domain requests that were rejected or domains that have been deleted.

A follow up question for @h-m-f-t here. Would expired requests that were neither rejected nor accepted go in an archive as well? I'm imagining these would be applications that were created but never submitted, or maybe submitted but then withdrawn.

**Comment by igorkorenfeld** [comment]
Following our conversation here is an [updated prototype](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FDesigns?page-id=4702%3A38556&type=design&node-id=4829-51217&viewport=607%2C209%2C0.2&scaling=min-zoom&starting-point-node-id=4829%3A51217&show-proto-sidebar=1) with the request summary move to domain management with a new section. 

Let me know if you all have any thoughts on this or if there is anything I missed in updating the UI.

**Comment by gabydisarli** [comment]
Looks good! I left one comment on the naming of the request archive page in Figma comments.

> the only items that would go in to this archive sections are either domain requests that were rejected or domains that have been deleted.


Following up on your reply from above. Wouldn't it make more sense to just call that bottom section Archive instead of 'Archived Domains'? Because there might be rejected requests down there too. Also domains can not have a status of archived so the title might imply they were archived.

**Comment by igorkorenfeld** [comment]
Great catch, it should be "Archive", I missed it when duplicating.

**Comment by gabydisarli** [comment]
@h-m-f-t Pinging you to get final sign off on these designs. I can work with engineering to make a new ticket for implementation. Here's a new [prototype link](https://github.com/cisagov/getgov/issues/697) since we are now working from a different instance of the Figma file.

**Comment by h-m-f-t** [comment]
LGTM, thank you!!
