### ISSUE TITLE
Add "withdrawn" confirmation email

### ISSUE THREAD

**Issue by neilmb** [cisagov/getgov#706]
### Ticket Description

Now that we are using a finite-state-machine transition method for withdrawing domain applications, we can add an email confirmation in that method, as described in [this document](https://docs.google.com/document/d/1I4sx-z2pbxdehj2Skci_sFZQvV8gEKE-nLu1CxxvaGc).

To add this email we need to

- [x] draft the email content
- [x] Add the templates and hook up `send_templated_email` in our `withdraw()` transition method

Note: see comments below the content is updated and this is ready for development
### Issue Type

development

**Comment by Katherine-Osos** [comment]
@abroddrick The content for this email has been approved and linked in my earlier comment. Looks like dev implementation is part of this same ticket, so letting you know it's ready.

**Comment by abroddrick** [comment]
Thank you so much I was wondering about this!

**Comment by abroddrick** [comment]
@Katherine-Osos I am removing you as assigned so that it appears clear for the other engineers. Otherwise I feel like it looks like someone is already working on this which you don't scroll down to the comments. Also removing the content label. Let me know if either is an issue
