### ISSUE TITLE
Provide an Admin the Approve Domain action

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#722]
### Story
In the Django Admin, regardless of the viewer, provide the capability to Approve an Application.

### Acceptance Criteria
The new "button" should execute the domain_application.approved() method.
approved domains should show in the registered domain section for the given user.

### Additional Context (optional)

ToDo: Confirm what state changes and notifications required integrated if applicable. Currently it can only go to approved from investigating and submitted. 
ToDO: Confirm what views needs to support this and how it integrates into the Analyst Experience Story Board.

### Issue Links

Relates to: #442

**Comment by brandonlenz** [comment]
Related to #285 per @rachidatecs
