### ISSUE TITLE
Produce a plan to successfully migrate current registrar users to our registrar

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#727]
### Story

As a group of stakeholders (engineers and business) provide a list of ideas to discuss how to successfully "migrate" users into the get.gov Registrar so that we can document work to achieve.

### Acceptance Criteria

- [x] Review the registrar sections 4.1 & 4.2 of the vendor transition plan
- [x] Essential COMMS drafted (Cameron)
- [x] Release Comms to users
- [ ] Users login to login.gov
- [ ] Invite users to the App

**Comment by michelle-rago** [comment]
[.Gov rollout communications plan](https://docs.google.com/document/d/1wXnYWV-lMBeuBQQnxHwWQezvCUx3mCliDUqWwssnIi0/edit)
