### ISSUE TITLE
Document the current process on OMB approvals

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/getgov#736]
### Story

As a designer/product manager I want to understand what the current process on OMB approvals is so that we can most closely replicate that experience or improve upon it for the MVP analyst application in Django Admin.

### Acceptance Criteria

- [x] A document/visual that details the current process for OMB approvals. This could be a story map, but the exact research artifact is TBD by the team. 
     - [Federal Executive Story Map for current experience documented (Miro)](https://miro.com/app/board/uXjVM-NqS_8=/?moveToWidget=3458764563666284119&cot=14)
- [x] Record any other actions as tickets or otherwise that require be taken.

    -  Added story map and related issue to content update ticket #576 

     -  ⚠️ Will likely need future stories related to discovery/design/implementation when this scenario is prioritized

### Additional Context (optional)

All federal executive domain requests need to be routed to OMB for approvals. Currently, this is handled manually by Cameron. See [Michelle's notes](https://docs.google.com/document/d/1xRxhJXf2n9_neB_zTNgqJbwmvo-Ss9v9mLxuyQOh6rg/edit). 

### Issue Links (optional)

Preceded by: #475
🔄 Relates to: [#501](https://github.com/cisagov/getgov/issues/501)  
[Slack thread with Cameron's responses](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1686948075496719) (needs to be formally captured)

**Comment by kitsushadow** [comment]
Future state: would be nice to automate the process to send OMB this information.
The work as a product of this is "later"

**Comment by gabydisarli** [comment]
[Federal Executive Story Map for current experience documented (Miro)](https://miro.com/app/board/uXjVM-NqS_8=/?moveToWidget=3458764563666284119&cot=14)
