### ISSUE TITLE
Fine-tune the logging for dev and sandbox

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#74]
The application should distinguish two logging levels automatically.

When DEBUG is turned on, logging should be tuned to provide information helpful for debugging during development.

When DEBUG is turned off, logging should be tuned to provide auditable information on user actions and system exceptions.

In all cases, the application is intended to run in a container and so logging should be to STDOUT.

(DEBUG in this case refers to the Django settings variable, not to a verbosity level.)

**Comment by calerubensteingsa** [comment]
9/27: Last PR has some changes to logging configuration, pending running for awhile

**Comment by calerubensteingsa** [comment]
9/29:

- More tuning may be nice
