### ISSUE TITLE
Setup CI pipeline to gate pull requests

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#75]
CI should run on every branch and should be able to include 
- Linting
- Pytest tests

We will run this with Github actions.

**Comment by loganmeetsworld** [comment]
Addressed in #85

**Comment by SSPJ** [comment]
Edited to remove Accessibility testing, as that will be tackled in #72

**Comment by loganmeetsworld** [comment]
This has been setup in #85, will be extended in other issues!
