### ISSUE TITLE
Adjust the "Investigating" Status to "In Review"

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#761]
### Story

As any user of the system and as the system itself, I want all references to the "Investigating" status to be switched to "In Review".

### Acceptance Criteria

Content and Application backend references to the "Investigating" status are replaced to "In Review".

### Additional Context

References:
https://cisa-corp.slack.com/archives/C05BDEA3C11/p1688146153700009 
https://docs.google.com/document/d/1I4sx-z2pbxdehj2Skci_sFZQvV8gEKE-nLu1CxxvaGc/edit?pli=1#heading=h.bey9gcaij94u

### Issue Links

🔄 #234
🔄 #731 
🔄 #554

### Tasks
- [x] Review and remove from Content
- [x] Review and remove from Backend. Solved by https://github.com/cisagov/getgov/pull/798

**Comment by gabydisarli** [comment]
@kitsushadow I don't believe we say the word "investigating" in any of the content. I just did a pass through of the info site and register. We always refer to the process as a review so I don't think there's anything to change from a content perspective. I can't make any changes to the application backend. Is this something we need to ping one of the developers for?
