### ISSUE TITLE
Accessibility/section 508 compliance for get.gov (info site)

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#768]
### Issue Description
Come up with a plan for reviewing accessibility compliance of the get.gov info site (unauthenticated public site). 
- Reach out to Trusted Tester consultant (Aaron) to request a review.
- Determine what the Trusted Tester needs to complete their review and provide it. (e.g. links to each page that needs to be tested)
- Agree on how issues will be documented

### Acceptance Criteria
- Entire site has been reviewed for accessibility compliance and tickets created for each identified issue.

### Additional Context (optional)
https://beta.get.gov/
https://beta.get.gov/domains/
https://beta.get.gov/help/
https://beta.get.gov/blog/
https://beta.get.gov/about/

### Issue Links
Dependency of: #752 
Depoends on #1035

**Comment by PaulKuykendall** [comment]
On June 16, Aaron was given the link: 
Aaron,

1-	You can go to https://getgov-stable.app.cloud.gov/. You’ll be prompted to create a login.gov sandbox account (I believe you may have created similar accounts in the past for other sites you were testing – let me know if not or if you have any issues).

2-	Once your account is created, I’ll give you admin access

3-	You can then login to https://getgov-stable.app.cloud.gov/admin

Rachid

**Comment by PaulKuykendall** [comment]
https://dhs.servicenowservices.com/oast?id=oast_form&table=x_dhsit_oast_ict_core&sys_id=ee1097801b087590fe4f6311f54bcb28&view=sp&spa=1#:~:text=a%20new%20record%3A-,ICTR0032453,-.%20Click%20here%20to

**Comment by PaulKuykendall** [comment]
Submitted updated request to Aaron to test the get.gov informational site, with the URLs in the description.

**Comment by PaulKuykendall** [comment]
Initial Report Received from Aaron Souza
[Get.gov - 508 Report.docx](https://github.com/cisagov/getgov/files/12052114/Get.gov.-.508.Report.docx)

**Comment by PaulKuykendall** [comment]
Created ticket #1035 for Dev work to be completed
