### ISSUE TITLE
Registrar Site: Create Plan for Accessibility Compliance

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#769]
### Issue Description
Come up with a plan for reviewing accessibility compliance. 
- Reach out to Trusted Tester consultant (Aaron) to request a review.
- Determine what the Trusted Tester needs to complete their review and provide it. (e.g. links to each page that needs to be tested)
- Agree on how issues will be documented

### Acceptance Criteria
- Entire site has been reviewed for accessibility compliance and tickets created for each identified issue.

### Additional Context (optional)
https://getgov-stable.app.cloud.gov/

### Issue Links
Dependency of #

**Comment by PaulKuykendall** [comment]
Created Ticket: ICTR0032457 in ServiceNow.

**Comment by PaulKuykendall** [comment]
Compliance Determination Form (CDF) Attached: 
[ICTR0032457 - .gov registrar CDF.pdf](https://github.com/cisagov/getgov/files/12353238/ICTR0032457.-.gov.registrar.CDF.pdf)

Also stored on Google Drive here:

**Comment by PaulKuykendall** [comment]
Closed, certification received.
