### ISSUE TITLE
Content: Clarify when AO will be contacted

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#783]
### Story
As a registrant
I want to know when my listed AO will be contacted
so that I can set expectations with the AO 

### Acceptance Criteria
The "Authorizing Official" step in the application process contains language that clarifies how and when an AO will be contacted.

### Additional Context
Concern/questions about contacting the AO came up in multiple user testing sessions. The concern was less that CISA would contact the authorizing official and more about needing to know how or when the contact would occur. Most wanted to be sure they had a chance to brief their authorizing official or prepare them for the conversation.  

Participants also voiced concerns about an application being delayed or rejected due to a lack of response from the AO (or other listed contacts).

**Comment by h-m-f-t** [comment]
In general, AOs _aren't_ contacted and we'll typically coordinate with the requestor. However, unique circumstances may dictate direct outreach. 

Even so, **let's remove the field for phone number**. Not asking for this information should ease concerns about outreach. I'm also comfortable including language like "Our practice is to coordinate with you, the requestor, before outreach to your authorizing official." 

Lastly, let's remove the field for middle name. We don't require that.

**Comment by Katherine-Osos** [comment]
I created two new issues related to this topic:

- AO Step: Remove middle name and phone number fields [#843](https://github.com/cisagov/getgov/issues/843)
- AO Step: Hide Opening Paragraph When "Federal" Org Type Selected [#844](https://github.com/cisagov/getgov/issues/844)

**Comment by Katherine-Osos** [comment]
[Content updates](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.2bn6wsx) approved on 8/9/23. Next, will update the UI.

See [slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1690926837597139) for convo about this ticket.
