### ISSUE TITLE
Create shortened names for the Organization Types

### ISSUE THREAD

**Issue by brooksr4** [cisagov/getgov#787]
### Story

As an Analysts
I want easily readable Organization Types
so that I can quickly sort and filter them.

### Acceptance Criteria

- The options for the Organization Type will read as follows
* Federal
* Interstate
* State or territory
* Tribal
* County
* City
* Special district
* School district

The labels in the table will be the same

### Additional Context

Note for Implementer: Ensure that this is not changed on the actual domain application, 
so when the domain application is going through the registrant does not see the shortened string

**Comment by h-m-f-t** [comment]
Yep.

An aside, ignore me: I can envision a future state where county and city governments are subsumed into an overarching "local" category with subcategories like "county". This affords us the opportunity to be clearer with small municipalities who don't see themselves in the "city" label (towns, townships, villages) and aligns with how the [Census Bureau categorizes local governments](https://www.census.gov/library/publications/2019/econ/2017isd.html) (in reality, CB categorizes special districts and school districts as local government too, but I think breaking those out is for the best).
