### ISSUE TITLE
Section 508 Accessibility Compliance - Django Admin

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#788]
### Issue Description

Verify compliance with Section 508 Accessibility requirements specifically for Django Admin Analysts Tool.

### Additional Context (optional)

URLs: 
https://getgov-staging.app.cloud.gov/admin/
https://getgov-staging.app.cloud.gov/admin/registrar/domainapplication/
https://getgov-staging.app.cloud.gov/admin/registrar/domainapplication/20/change/

### Issue Links

Dependency for: #752

**Comment by PaulKuykendall** [comment]
Initial Assessment for Django Admin


[dotgov.-.508.Report.docx](https://github.com/cisagov/getgov/files/12005145/dotgov.-.508.Report.docx)

**Comment by PaulKuykendall** [comment]
To clarify Test Result 2 - per Aaron Souza (Teams Chat)

> For #2, the way the table is grouped is not correct due to the way it is currently structured. The data cell is only associating it with the row header. You can't have headers and row on the same level. Headers come before the data cells. So if you add you were to add another row above, basically having naming convention to associate to all of the rows bellow then that would be understandable. For example, Registrar would be the column header and rows bellow would be associated with it.

https://www.w3.org/WAI/tutorials/tables/

**Comment by abroddrick** [comment]
@PaulKuykendall did you get clarification on #3's comment about the checkbox being "Programatically labeled" ? I'm assuming that this refers to a label for screen readers being needed, but I want to be sure we are on the same page

**Comment by PaulKuykendall** [comment]
Didn't mean to close this.

**Comment by abroddrick** [comment]
@PaulKuykendall what is the AC for this ticket? This reads to me as a a check to read the findings and determine action items and I want to be sure we are on the same page.

**Comment by h-m-f-t** [comment]
Final (?), approved section 508 report ([Drive](https://drive.google.com/file/d/101JW7rNUOofrplTXe3sEiiMdYSWLcQoZ/view?usp=drive_link)). Original is at "Your CDF regarding ticket number regarding ICTR0032457 has been generated", 7/19.

**Comment by PaulKuykendall** [comment]
@h-m-f-t the above approval applies to the Registrar. I am requesting a re-test of the DjA tool. Each of the three "components" will have their own CDFs.

**Comment by PaulKuykendall** [comment]
Requested retest from Aaron. Expecting results later this week. (August 18)

**Comment by PaulKuykendall** [comment]
Received Sec 508 CDF and logged into Google Drive.
