### ISSUE TITLE
Django admin "log out" doesn't log a user out

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#794]
### Current Behavior

On the admin page, when you click  "log out"  in the upper right corner, nothing happens

### Expected Behavior

When clicking log out, you should be logged out of the application

### Steps to Reproduce

1.got to \admin
2. click  "log out"  in the upper right corner
3. notice the sound of crickets as nothing happens

### Environment

environrment: stable or local
Browser: Chrome  114.0.5735.198

**Comment by zandercymatics** [comment]
Reopened as I am unsure as to if the originator should close this
