### ISSUE TITLE
Analyst changes domain to Ineligible status

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#797]
### Story

As a analyst
I want change a domain status to INELIGIBLE 
so that a **user is blocked** and cannot  send anymore domain request or make any edits to their existing/in progress domains or domain applications

### Acceptance Criteria

AC:

- Analyst on the admin pages should be able to see ineligible as a status for domain applications
- analysts should be able to save a domain application as ineligible which will set a flag on the User that indicates ineligible (name of flag is up to developer)
- No edits or changes allowed on this domain/domain application or other existing domains/ domain applications **by this user** while in this state 
- No new domain requests allowed for this user while in this state
- the domain applicant should still be able to view what they submitted
-all other Approved domain requests (by the same user) be changed to ineligible while in this state (note there should be a check added in the future for  is_active but that is out of scope)
- in review and submitted applications can’t be modified by an analyst or the user in question, but do not change to ineligible status.
-see status document for what states can change to ineligible 

NOTE to developer:
This can be broken into smaller tickets or multiple PRs as needed
-suggestion s (see #811 )
### Additional Context
[see slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1692376201067369)
see [this slack thread](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1689200833336109)
see the [status transition](https://docs.google.com/document/d/1no29E2c9QWIHf_2wv3GCy6AotZ2_PVbIBiavKW-opxE/edit) doc as the source of truth on allowable actions

### Issue Links

Relates to: #873

**Comment by h-m-f-t** [comment]
> should domains in any state be able to changed to ineligible?

See [comment in status doc](https://docs.google.com/document/d/1no29E2c9QWIHf_2wv3GCy6AotZ2_PVbIBiavKW-opxE/edit?disco=AAAA0-qcT4w)

**Comment by abroddrick** [comment]
@Katherine-Osos @gabydisarli @brooksr4 I think all the questions for this one have been answered, but does this require separate tickets for any design changes? Such as maybe error messaging to let them know why they can't do anything
