### ISSUE TITLE
Add initial security scanning for Django application code

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#80]
- Turn on dependabot alerts 
- Investigate various options for security scanning through github actions https://github.com/marketplace/actions/django-security-check
- Contemplate adding Zap scanning:  https://github.com/18F/django-template/blob/main/django_template/templates/github/workflows/owasp-scan.yml.jinja#L44-L51

**Comment by loganmeetsworld** [comment]
This will be an add on, if necessary after #81

**Comment by loganmeetsworld** [comment]
From a team member in Slack: 

OWASP publishes docker images for Zap and if you already have your app set up in docker-compose, then you can add their images under a separate profile (so that container won’t start when just running the app locally) and then [run zap scans whenever you want with docker-compose run owasp](https://github.com/18F/django-template/pull/11/commits/1b212e486851a426eef482cb6ab0003cf8b8fe44#diff-0f463ed90dd8d656d46cc46c6f229d255c62d754813acf83c2a7866d9bcde5f1).

They also publish [Github actions for scans](https://github.com/18F/django-template/blob/main/django_template/templates/github/workflows/owasp-scan.yml.jinja#L44-L51).

**Comment by calerubensteingsa** [comment]
10/6:

- Github actions setup, there is a PR, runs Django security check command also runs external scanning tool from OASP, all runs in Docker compose in Github actions.
- Will get review from Seamus or Logan

Logan:
- Does it run on every push or just on open pull requests - the latter.
