### ISSUE TITLE
Provide a way for analysts to put domains into clientHold

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#803]
### Story

As an analyst
I need to put a domain in clientHold 
so that it's paused from resolving in the .gov zone.

This is for _domain objects_; the domain request must not be deleted.

### Acceptance Criteria

An analyst can put a domain on clientHold to prevent resolution.
An analyst can remove the clientHold status.

### Additional Context

Implementation Note: 
* This ticket doesn't include _actually setting a domain on clientHold_, which is an EPP function (see #857). It should, however, do the work necessary up to the point of 857.
* * Use an action button on Django Admin to trigger the function (clientHold). 

This issue can presume that the mechanism whereby an analyst is made aware about (and validates the authenticity of) a delete request occurs via some other process (which is ripe for future innovation).

~~Question: does this affect existing db setup?~~

### Issue Links

Blocks #804 
Depends on #964

**Comment by abroddrick** [comment]
for refinement:

**Comment by h-m-f-t** [comment]
@kitsushadow thanks! I made a number of revisions in an attempt to increase clarity.

**Comment by Katherine-Osos** [comment]
Is clientHold a status? If not, should we make that assignment filterable so analysts can quickly find all that are on clientHold?

**Comment by h-m-f-t** [comment]
@Katherine-Osos, clientHold is a _domain_ status, but it is not a _domain application_ status.
