### ISSUE TITLE
Analyst view of domain management data

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#806]
### Story

As an analyst
I want to be able to view all data entered in the domain management pages for a given domain
so that I can easily see and modify contact, host and other dns info 

### Acceptance Criteria

- For approved domains, analysts can view all domain management information clearly (see the domain overview page example in additional context)
- This data should be editable
- Optional: have some data editable while others are not (requires refinement and can be added on later).

If option 2 (see below) is implemented:
- The button in Django admin should read “Manage Domain”
- The domain management page should open in a new tab. Within that tab, remove the “Back to manage your domains” button (for analysts only) 
- Show an alert message at the top of the Domain Management page telling analyst that they are viewing someone else’s domain and should close the tab when finished. Gaby created a [Figma mock-up to show what this could look like](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=491%3A26602&mode=design&t=uTSNRvle2VbI9pA4-1).

### Additional Context

It is important to be able to see which contacts are associated with a given domain's management, especially when needing to reach out to them. In the current system, analysts can view all domain management data but can only edit some data.

- One option is to make a view on django admin to show all this data nicely to match the domain overview page. Most data is already able to be retrieved from Domain Information, the exception is the epp centric stuff.
- Option 2 is to have a button on djano admin domain page link the analyst to the correct domain management page. Here it would be good to add in logging to indicate that the actions are being carried out by an analysts. 

for context, this is the domain management page that users see and which has all the data that an analyst needs to see. 
![image](https://github.com/cisagov/getgov/assets/109625347/7b2c5441-fbe3-43e3-9e91-adfa189d2e7e)

for refinement:
1. would option 2 be confusing for analysts as the domain management page has a section called "Your Contact information"
2.) is this going to require using the Public Contact class?

### Issue Links
relates to: #807 
_No response_

**Comment by zandercymatics** [comment]
Updated the AC to reflect recent revisions and scope changes
