### ISSUE TITLE
Epplib: Update xml contact Parsing for InfoDomainResponse-contact field

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#809]
### Current Behavior

InfoDomainResponse objects aren't showing the contact values from the registry. Even when a domain clearly has contacts, the contacts won't appear following a InfoDomain request.

### Expected Behavior

Contacts should exist in the InfoDomainResponse object

### Steps to Reproduce

1. open shell into a sandbox envirornment
cf ssh getgov-ENV
/tmp/lifecycle/shell
./manage.py shell
2. insert commands to see the xml of the info request on a domain that has contacts
from epplib.models import common
from epplibwrapper import CLIENT as registry, commands

registry._client.connect()
registry._client.send(registry._login)

registry._client.transport.send(request.xml())
response = registry._client.transport.receive()
print(response)
3. view the infoDomainResponse object created by the parser
request = commands.InfoDomain(name="starwars.gov")
response=registry.send(request,cleaned=True)
print(response)

4. see contacts is missing after it's parsed but the xml is correct

### Additional Context

Possibly is being caused by the tag element that it doesn't look like the library was expecting. I think just parsing for the "type" as well should help. The contact return list should also be modified so that it is a dictionary of type {contactType: string, "registry_id":id} (a custom object may be ideal for this).

### Issue Links

Blocks: any epp retreival actions regarding contacts

**Comment by zandercymatics** [comment]
Can't seem to run 'registry._client.connect()', returns the error: `
File "/home/vcap/deps/0/python/lib/python3.10/site-packages/epplib/transport.py", line 103, in connect
    context.load_cert_chain(certfile=self.cert_file, keyfile=self.key_file, password=self.password)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3900)`
I have verified this with @rachidatecs , he is running into the same issue

**Comment by zandercymatics** [comment]
Blocked on this item

**Comment by zandercymatics** [comment]
Something to note: you can get contacts to appear if you use this command:
print(response.res_data[0].contacts)

**Comment by zandercymatics** [comment]
@abroddrick Did you want me to close this or keep it up? I have the behavior fix over on EppLib but its not necessarily a bug either - thoughts?

**Comment by abroddrick** [comment]
This didn't get closed when it was marked as done, should be closed.
