### ISSUE TITLE
Admin | Sort all drop-downs alphabetically

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#813]
### Story

As a CISA Analyst
I want to see all options in dropdowns sorted alphabetically in Django Admin
so that I can more easily locate my selection.

APPLIES to AO (Authorizing official), requested domain, submitter, creator.

### Acceptance Criteria

Dropdown box selection options are presented in alphabetical order.

**Comment by zandercymatics** [comment]
@PaulKuykendall Hey Paul, quick question about the scope of this ticket... The ticket mentions that this only applies to four fields: AO (Authorizing official), requested domain, submitter, creator. That said, there are a few other fields on the /admin site which present a list of users out of alphabetical order, such as investigator or 'user'. Should this also apply to those, or just to the listed fields
![image](https://github.com/cisagov/getgov/assets/141044360/f9cab064-504a-4ece-91ca-00a17c436801)

**Comment by zandercymatics** [comment]
Note: I've spoken to Paul about this ticket and he mentioned that this applies to most dropdowns in /admin. The exception would be 'special' fields where order does matter: i.e. organization type
