### ISSUE TITLE
Domains approved in admin show up with status "None" in Registered Table

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#818]
### Current Behavior

If a domain is changed in django admin to be approved, it shows in the registered table with a status of "None" even after refreshing the page. 

![image](https://github.com/cisagov/getgov/assets/109625347/3793e601-89b3-4ccb-81e8-475aca3faed5)

### Expected Behavior

When a domain is approved by an analyst in django admin, then it should show the status "approved" in the registered table.

### Steps to Reproduce

1. In django admin, locate a domain application that is in the "in review" state
2. Approve the domain application
3. navigate back to the home page of the application and look at the Active Domains table

### AC

When a domain application is approved, the domain application status should show as approved

### Environment

Stable and local 
Chrome & Safari

### Additional Context

Note, while the Registered domain section doesn't show the proper status, it does show the correct "approved" status in the Active Domain Request section. This may help with debugging, however, this ticket does not cover fixing the domain application from appearing in both locations that is covered in #796.  

### Issue Links

Relates to: #796 
Relates to: #701

**Comment by gabydisarli** [comment]
@abroddrick should we just adjust this ticket to be the implementation ticket for #697 ?

**Comment by abroddrick** [comment]
I think this is a rare occasion where I will render this ticket a won't do. That way if anyone sees this bug before we remove the status column, they can see it was documented previously and determined irrelevant.

**Comment by abroddrick** [comment]
reopened because this is actually a sign that we have something wrong with how the status is being set. A domain application should actually have the correct approved status if it is approved, whether we show it or not.
