### ISSUE TITLE
Update the home page to match small design changes

### ISSUE THREAD

**Issue by abroddrick** [cisagov/getgov#822]
### Issue Description

Follow [ this figma](https://www.figma.com/proto/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?page-id=4702%3A38556&type=design&node-id=4829-51217&viewport=-1054%2C72%2C0.29&scaling=min-zoom&starting-point-node-id=4829%3A51217&show-proto-sidebar=1) in order to remove the status column from the Registered domain section on the home page and add change the Archived Domains title to Archive. 
AC:
- remove the status column 
- change the title for the archived domains
- edit existing tests if applicable
- ensure that everything in the figma now matches the updated page.

### Additional Context (optional)

Design determined the status wasn't needed for a registered domain, because all of them should be approved. See #697 for more background on design discussions if desired. 

### Issue Links

Created from #697 
Renders #818  a won't do

**Comment by abroddrick** [comment]
@gabydisarli  does this successfully capture the ticket what is discussed in #697

**Comment by abroddrick** [comment]
@zandercymatics  for the most part you will just have to edit src\registrar\templates\home.html for this one. See the h2 tags  for Registered domains and Active domain request. under the Registered domains h2 tag you will see a tr for table row and th for table header, remove the th line that has the term status. Then in the section below you will see <tbody> remove the status line from being added. 

The archived domains label change should be pretty straight forward there.

see the readme on running tests locally and double check no tests are failing when these are changed. You may have to update tests that are looking for those status or archived domain labels.

**Comment by zandercymatics** [comment]
@abroddrick Since we are removing Status, will the DB object also need to be changed to remove this inclusion, or is it used elsewhere in the app? Once I am able to get the app running + able to test, I'll also remove it from index.py (as no data is being passed) unless that has some downstream affects.

With regards to testing/collectstatic, I am roadblocked on that end with the manage.py issue (usr/bin/env: 'python\r' no such file or directory)... Currently troubleshooting that but I've identified that the issue is with the line endings

**Comment by abroddrick** [comment]
@zandercymatics good question! No it would need to stay in the db object as it is going to be used elsewhere. That makes sense to remove it from index.py I don't imagine that having any negative effects. Glad you identified the issue, do you need additional help with troubleshooting it?

**Comment by zandercymatics** [comment]
@abroddrick Ah alright, I'll leave the db object alone, thanks! I do not need any assistance for now, I know what to change and where but I do not have a way to test these changes until everything gets setup (cloud, db credentials, django secret keys). I imagine the issues I'm running into now with the 500 error / broken css style sheet are related to that missing info

After some of the CF issues get resolved I may need your assistance with some of the credentials if I run into an issue there

**Comment by zandercymatics** [comment]
@abroddrick On the figma, there is a slight verbiage difference under 'archive', a similar thing with 'Export Domains' as well. In addition I noticed that the color scheme is ever so slightly different, should these changes be followed or is it leftovers from days old?
(red is figma, blue is the environment now)
![image](https://github.com/cisagov/getgov/assets/141044360/1abbac61-61b3-4fa5-829d-86d1eaad941e)

**Comment by abroddrick** [comment]
Yes I would say to change the verbiage differences there too @zandercymatics, this was probably just missed during refinement. I would ask @gabydisarli, @Katherine-Osos or @brooksr4 about the color scheme difference. Particularly if the color schemes needs to change for the whole application, in which case that should be it's own ticket.

**Comment by zandercymatics** [comment]
@abroddrick Alright, I'll make those amendments so that it better matches the design. I believe I have a meeting with @gabydisarli later this afternoon to assist with her environment setup (if her schedule permits), so I will bring that up with her then

**Comment by gabydisarli** [comment]
Sorry for the confusion @zandercymatics. To give you some context, the way the Figma was designed in the past, it was not kept up to date with implementation as design and styling were iterated on in the code. I understand this is confusing and it throws me off too! For verbiage, yes match the Figma, for the color scheme difference, keep what is currently implemented as that is the most up to date.

**Comment by zandercymatics** [comment]
Issue was withdrawn
