### ISSUE TITLE
Design - Alert user to certain domain status changes

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#824]
### Story

As a domain registrant
I want to know if my domain status has changed in certain instances
so that I understand what state it is in

### Acceptance Criteria

- Design and messaging are finalized to inform user when their domain is in a state other than active due to a domain status change

### Additional Context

If a domain status (not application status) is e.g., clientHold or Deleted, the domain will be inactive even if the _application status_ implies that it should be active. Currently the UI only displays the application status (e.g. Approved).

We need to alert users that the inactive state is intentional and provide messaging why.

See [status document](https://docs.google.com/document/d/1no29E2c9QWIHf_2wv3GCy6AotZ2_PVbIBiavKW-opxE/edit#heading=h.49x2ik5), which describes these domain statuses.

**Comment by Katherine-Osos** [comment]
@kitsushadow The AC in this ticket will be addressed in https://github.com/cisagov/getgov/issues/929. It can be closed.

**Comment by PaulKuykendall** [comment]
@Katherine-Osos and @kitsushadow  - Are we sure that #929 will address this #824? 

929 speaks to the displayed status for the user, whereas 824 seemed to imply Alerting to the user, presumably in the form of an email.

Am I misunderstanding 824?
