### ISSUE TITLE
Write a Open Gov proposal

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#83]
- [x] Write a 2-3 sentence description of the program that can be aligned with the plan for Phil to have
- [x] Within next 7-10 days: Send Phil a few paragraphs describing alignment with the action plan and proposed commitment
  - Current status of program
  - How it aligns with plan and principles
  - Overview commitment to be achieved by 2024

**Comment by h-m-f-t** [comment]
[Draft ](https://docs.google.com/document/d/1vJ4XsRq7xqPMHKffIcGRXzzspwq4NJsIIT_FjdaIv3Q/edit?usp=sharing) for the draft reviewers

**Comment by loganmeetsworld** [comment]
Written and sent!
