### ISSUE TITLE
Offboard Colin

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#84]
# Onboarding checklist 

- [ ] Remove from Github and @cisagov/dotgov team
- [x] Remove from private Google drive and Google group
- [x] Remove from Slack group and both Slack channels
- [x] Remove from Team Charter

Success is Colin no longer has access to private project, technical or user data

**Comment by colinmurphy01** [comment]
Pour one out for me.

**Comment by loganmeetsworld** [comment]
@h-m-f-t to remove from Github.
