### ISSUE TITLE
Manage Submitted Application: Missing "back" button

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#865]
### Issue Description

After submitting an application (before it's approved), there is a page where applicants can review their info and withdraw the application. There should be a button at the top of the page that allows users to navigate back to the main dashboard. Button should read: Back to manage your domains

[See Figma file for mockup](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=3124-32294&mode=design&t=o2OwvukeXRaSm95f-0).

### Acceptance Criteria
- If an application is submitted then a user should be able to view there application info and have a back button
- Back button should take them back to domain management page
  - Note: See Figma for a submitted domain. Look for the blue back button in the upper left. 

### Additional Context (optional)

For reference: In the prototype, this button is currently displayed on the domain management pages for an approved domain. You can reference that for existing styling in the UI.

**Comment by h-m-f-t** [comment]
Aside from it existing in Figma, why do we think this is needed, particularly when there's a back button in every browser?

**Comment by Katherine-Osos** [comment]
@h-m-f-t In general, best practice is to never lead users to a dead end; you need to offer somewhere else to go. This can be achieved in a variety of ways (e.g. on a news site, suggest related articles; on a banking site, suggest related actions like "pay your bill"). On the registrar, there aren't many actions to suggest, and certainly none that we're trying to "push." We don't want to push people to create another domain request, for example. Therefore, the natural escape hatch would be to suggest returning to the dashboard. Note: on the current registrar, the navigation is exposed on every page, which is another option for avoiding a dead end (although I'm not suggesting we do that).

The browser "back" button is problematic for a couple reasons. One, it assumes the user is accustomed to using that for navigation, which isn't always the case. Two, using the browser "back" button doesn't always lead where users expect; and on authenticated sites, it could inadvertently log you out. It's risky and some users will be tentative to trust it. Therefore, a custom "back" button can waylay those fears because it's integrated into the experience and (hopefully) users will have faith it leads where they expect. [This article](https://www.smashingmagazine.com/2022/08/back-button-ux-design/) kind of gets at what I'm trying to say.

**Comment by abroddrick** [comment]
Reserve this one for Nicolle to do. It looks like a good first ticket
