### ISSUE TITLE
Sprint Goals 27

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#871]
### Objectives:
EPP Backend
EPP integrations Frontend
Transition / State Documentation
Moratorium Experience
Manage My Domains
Domain Applicant
Analyst Experience
User Migration
Data Migration
___________________________________________________________________
EPP Backend
- #847 
___________________________________________________________________
EPP integrations Frontend
- 
___________________________________________________________________
Transition / State Documentation
- 
___________________________________________________________________
Moratorium Experience
- https://github.com/cisagov/dotgov-home/issues/158
___________________________________________________________________
Manage My Domains
- #860 
- #796 
- #861 
- #507 
___________________________________________________________________
Analyst Experience
- #806 
- #797 
___________________________________________________________________
User Migration
- #727 
___________________________________________________________________
Data Migration
- #727 
___________________________________________________________________

**Comment by PaulKuykendall** [comment]
Removed - #778 . This will be scheduled in a future sprint.
