### ISSUE TITLE
Create list of test cases for domain management & admin

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#887]
### Issue Description

Document test cases for critical experiences in the registrar and Django admin:

- [x] Dashboard Functions
- [x] Manage Domains
- [ ] Admin Functions

As appropriate, also document user scenarios that should _not_ work. 

### Additional Context (optional)
Test cases are being documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1nu1-rggnTZmdCI7semiLOJhwakkmMLKafvqThahzeOU/edit#gid=1274873230).

**Comment by PaulKuykendall** [comment]
In Sprint planning, decided that this belongs in Sprint 27, but needs clarity and refinement.
