### ISSUE TITLE
R1 Recruitment Outreach / Scheduling

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#9]
- [x] List of candidates created
- [x] Emails drafted
- [x] Slots created
- [x] Emails to be sent week of 9/5
- [x] Schedule debriefs

Success = Interviewee and date is confirmed

**Comment by colinmurphy01** [comment]
Consideration: Can create appt slots in shared calendar and make it public?

**Comment by colinmurphy01** [comment]
Consideration: Outreach goes out from the .gov email account and sent by Cameron, possibly individuals CCed

**Comment by colinmurphy01** [comment]
@boonerang I spun this up as a placeholder, but since we prioritized current state research for R1. It seems there's not much outreach needed outside of cameron and others to complete our initial workstreams involving content, screens, flows, roles/responsibilities. 

I'm thinking we should close this and then we can build out a outreach/recruitment tickets for the qualitative research with existing and potential customers.

**Comment by colinmurphy01** [comment]
I'm going to move this back into the backlog for consideration as we begin recruiting for the Qualitative Research next sprint.

**Comment by igorkorenfeld** [comment]
Created public calendar slots and sent out individual time blocks
