### ISSUE TITLE
Get and Post the Registrant name and emailing address (EPP)

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#915]
### Issue Description

On the domain management page, Registrant name and emailing address needs to pull from EPP and call the set commands when data is saved.

**Comment by abroddrick** [comment]
I think this needs to be marked as a won't do, I asked if the current Your Contact section ties to a registrant on the domain [in slack](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1692648256772489?thread_ts=1692648232.285899&cid=C05BDEA3C11) and it seems this was not the intent, instead the intent was to just be a user contact update field. I think for MVP we will not need to change the registrant past setting it to the default values

**Comment by abroddrick** [comment]
@h-m-f-t  would you mind confirming that the domain registrant won't need to be  edited on the domain management page for MVP?

**Comment by h-m-f-t** [comment]
See discussion at https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1692798442821049
