### ISSUE TITLE
Update TBD Get Help link on Domain Name Servers page

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#916]
### Issue Description

On the domain name servers page there is still a link with get help with domain servers. To see this go to an approved application in the Registered domain section, click the manage icon. Click the Domain name servers tab, then on that page see the llnk that reads"Get help with domain servers.link TBD". This is the link in question.

### Additional Context (optional)

REFINEMENT:
-is a content change needed here?
-what link to change it to?
_No response_

**Comment by Katherine-Osos** [comment]
This was addressed in #766
