### ISSUE TITLE
Commit initial database models

### ISSUE THREAD

**Issue by SSPJ** [cisagov/getgov#92]
- [x] write an ADR for the models and fields we can include right now
 - [x] create a pull request to include them
 - [ ] create a work-in-progress git branch on which to continue brain-storming and diagraming models

**Comment by colinmurphy01** [comment]
Reduce scope down to a user model at a minimum

**Comment by calerubensteingsa** [comment]
- Commit user and profile model

**Comment by calerubensteingsa** [comment]
9/22:

- Limited scope, just about user model - Seamus explained yesterday that the strictly the user model goes with the login.gov authentication, if we want to add additional information like content information beyond email, need separate DB table

Building that now, got description on local machine. Page to change display name. A way to practice implementing those things in Django.

**Comment by calerubensteingsa** [comment]
9/27:

- In PR, ADR draft linked in Slack - in Google Doc, if anyone is curious - has to do with user information. Seamus reviewed and good to go
