### ISSUE TITLE
Data Migration: Domain Invitation Email send

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#927]
### Issue Description

We will be sending emails separate of data ingestions. We want to avoid inviting already invited users while being able to update data from the to-end registry.
- For users with more than one domain, only send one email but include the links to all their domains not just the single domain.
- This script is a one time design for use with the migration. 
- This script should be able to be run multiple times with new sets of data, if the domain invitation has already been sent then it should NOT re-send for that email address 
  - The email is sent when transition_domain.email_sent=False. It should update this field in the table as it sends the emails. 
  - Ensure this is true even in the case where one user has multiple domains (all those domain rows should now have the same flag switched
- This should be VERY well tested. Include tests in the script or in a supporting script. Do not use it in production or with the actual emails from our host data until we are ready to execute the user Migration into our system. Test with fake emails or emails from team members.

### Additional Context (optional)

NOTE: Use the current domain invitation verbiage, run it by design to ensure it will be good given that it is for the migration vs normal invitations. 
https://docs.google.com/document/d/1UkQZdAmcGprXWdHX_PuT155CCNPbf_Gf/edit?pli=1#heading=h.iqv2v8lecjpn

retest this after #923 is done with all the data from verising
### Issue Links

blocked by: #923

**Comment by dave-kennedy-ecs** [comment]
Below are previews of two sample emails to be sent during migration.  These are added here for additional refinement.

First email is sent to a domain manager with only one domain to manage:

![domain manager with single domain](https://github.com/cisagov/getgov/assets/111779554/a647e1b4-934b-438e-9bd2-1a00a28d697f)

Second email is sent to a domain manager with multiple domains to manage:

![domain manager with multiple domains](https://github.com/cisagov/getgov/assets/111779554/cf53d835-3d94-4256-b4da-0587603b813c)
