### ISSUE TITLE
UX: Administrative Reports

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#938]
As an Analyst, I want to access certain reports from my dashboard in a logical and convenient way, so that I have easy access to meet program needs.

Please research and design a UX for reports based on MVP requirements listed in Epic: #936

AC:

- [x] work with @rachidatecs for UI design details in DjAdmin. (mockups if necessary, or straight to implementation) with sufficient detail to inform back-end/database designs and architecture.
- [x] Decision on data sourcing for these 4 MVP reports (@rachidatecs)
- [x] Tickets created, as necessary, for data/engineering work
- [x] Update [User Test Sheet](https://docs.google.com/spreadsheets/d/1nu1-rggnTZmdCI7semiLOJhwakkmMLKafvqThahzeOU/edit#gid=1362437238) with these UAT test cases. (This work will be done as part of #887 )

**Comment by brooksr4** [comment]
I created the following stories as a result of this ticket: #996 #997 #998 #999

**Comment by h-m-f-t** [comment]
After reviewing #996 #997 #998 #999, I'm confident the core work of this task is done. There are still two more A/C which haven't been checked off; tagging @rachidatecs and @Katherine-Osos for those (and cc: @PaulKuykendall).

**Comment by brooksr4** [comment]
@h-m-f-t based on my discussion with @rachidatecs data sourcing for the all reports besides the Domain Growth one will come from the fields that are already in the database from the the registrar application.

@PaulKuykendall  we can get a little more crisp on the actual fields that each report column equals for each report. That work should probably be part of the individual reports.

As far as the User Test Cases, @Katherine-Osos is adding these test cases as part of #887
