### ISSUE TITLE
Ensure AC-8 is effectively implemented

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/getgov#949]
### Issue Description

To meet [AC-8](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf#page=67), we should:
- [x] ~Determine approach~ Do what [USAjobs.gov](https://www.usajobs.gov/) does (click "Sign in", or [see it here](https://login.usajobs.gov/wsfed?wtrealm=https%3A%2F%2Fwww.usajobs.gov%2F&wa=wsignin1.0&wreply=https%3A%2F%2Fwww.usajobs.gov%2Fsignin-wsfed&wctx=CfDJ8C8ubvm2gVtLnxO3imZ94-vwYNmI0cUbojmWtEOg1u0idJp_Uvvpvc99fz8Arl3p33RmpUr7jOGHgawbAmQuch96EE7ggQJzL9ljkkmpeN75RWgBmFnHK5SBae8y-a9xS1jZSQkAn4rtBG5D6YsePB262331YIJLqlJJZG7Lr1gyFqZWFFipwOqfvBjufTIy8104YaGoj8S1xPW9QfcLKKgdFmNrwWLwjH_NEvnvhFKvnUH-5xVfhyoViTAhsWp9ZqnZMWXISkGZl_816LRT906ECunm4g5FxlkV6JoMXJbctAxm3ogs8nHC-GhF_DfhVoCZl93t9sw_wDyJu85IVCo))
  * [cloud.gov's approach and language](https://login.fr.cloud.gov/login)
  * [Global Entry's approach and language](https://ttp.dhs.gov/)
- [x] ~Determine text~ Pull from [intranet](https://dhsconnect.dhs.gov/org/comp/mgmt/ocio/ciso/Pages/sspolicy.aspx) (requires VPN)

**Comment by h-m-f-t** [comment]
Next steps are to figure out where/how USAjobs.gov [includes the information blurb](https://login.usajobs.gov/wsfed?wtrealm=https%3A%2F%2Fwww.usajobs.gov%2F&wa=wsignin1.0&wreply=https%3A%2F%2Fwww.usajobs.gov%2Fsignin-wsfed&wctx=CfDJ8C8ubvm2gVtLnxO3imZ94-vwYNmI0cUbojmWtEOg1u0idJp_Uvvpvc99fz8Arl3p33RmpUr7jOGHgawbAmQuch96EE7ggQJzL9ljkkmpeN75RWgBmFnHK5SBae8y-a9xS1jZSQkAn4rtBG5D6YsePB262331YIJLqlJJZG7Lr1gyFqZWFFipwOqfvBjufTIy8104YaGoj8S1xPW9QfcLKKgdFmNrwWLwjH_NEvnvhFKvnUH-5xVfhyoViTAhsWp9ZqnZMWXISkGZl_816LRT906ECunm4g5FxlkV6JoMXJbctAxm3ogs8nHC-GhF_DfhVoCZl93t9sw_wDyJu85IVCo) at sign-in-time. I've scoured https://developers.login.gov/ and don't see anything. Perhaps @neilmb knows?

**Comment by h-m-f-t** [comment]
Custom text can be added in Identity Sandbox inside the app after it's already been created.

This is now complete.
