### ISSUE TITLE
Get.gov: Add more AO examples to Eligibility page

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/getgov#992]
### Story

As a domain registrant
I want to better understand who qualifies as an AO
so that I list the correct person in my application.

### Acceptance Criteria
**Eligibility page**
- Add more examples of qualifying AOs to the Eligibility page on get.gov: https://beta.get.gov/domains/eligibility/
- Content changes should be reflected in [this document](https://docs.google.com/document/d/1Q96zwCNSzTBTEUX7fJXiYx2wdhqN_ijvTkHufwi01oo/edit#heading=h.tyjcwt).

**Help > Domain Requests page**
- Update the AO language on the Domain Requests help page: https://beta.get.gov/help/domain-requests/
- Content changes should be reflected in [this document](https://docs.google.com/document/d/1U7MLSXvDJsAxfEzPdKXoy6-wBL9IKynJ9JLDHTrEjxY/edit#heading=h.1t3h5sf)

**Comment by h-m-f-t** [comment]
Though this is the "live experience", I'm staging this for sprint 29 because it needs to be updated before we release October comms.
